/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedBodyRouteImport } from './routes/_authed.body'
import { Route as AuthedCalendarRouteImport } from './routes/_authed.calendar'
import { Route as AuthedFleetRouteImport } from './routes/_authed.fleet'
import { Route as AuthedListsRouteImport } from './routes/_authed.lists'
import { Route as AuthedMoneyRouteImport } from './routes/_authed.money'
import { Route as AuthedNotesRouteImport } from './routes/_authed.notes'
import { Route as AuthedPantryRouteImport } from './routes/_authed.pantry'
import { Route as AuthedPlacesRouteImport } from './routes/_authed.places'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed.settings.index'
import { Route as AuthedSettingsAccountRouteImport } from './routes/_authed.settings.account'
import { Route as AuthedSettingsAppearanceRouteImport } from './routes/_authed.settings.appearance'
import { Route as AuthedSettingsDevicesRouteImport } from './routes/_authed.settings.devices'
import { Route as AuthedSettingsHouseholdRouteImport } from './routes/_authed.settings.household'
import { Route as AuthedSettingsNotificationsRouteImport } from './routes/_authed.settings.notifications'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBodyRoute = AuthedBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFleetRoute = AuthedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedListsRoute = AuthedListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMoneyRoute = AuthedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotesRoute = AuthedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPantryRoute = AuthedPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlacesRoute = AuthedPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAccountRoute = AuthedSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAppearanceRoute =
  AuthedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsDevicesRoute = AuthedSettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsHouseholdRoute = AuthedSettingsHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/body': typeof AuthedBodyRoute
  '/calendar': typeof AuthedCalendarRoute
  '/fleet': typeof AuthedFleetRoute
  '/lists': typeof AuthedListsRoute
  '/money': typeof AuthedMoneyRoute
  '/notes': typeof AuthedNotesRoute
  '/pantry': typeof AuthedPantryRoute
  '/places': typeof AuthedPlacesRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/join/$code': typeof JoinCodeRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/appearance': typeof AuthedSettingsAppearanceRoute
  '/settings/devices': typeof AuthedSettingsDevicesRoute
  '/settings/household': typeof AuthedSettingsHouseholdRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/body': typeof AuthedBodyRoute
  '/calendar': typeof AuthedCalendarRoute
  '/fleet': typeof AuthedFleetRoute
  '/lists': typeof AuthedListsRoute
  '/money': typeof AuthedMoneyRoute
  '/notes': typeof AuthedNotesRoute
  '/pantry': typeof AuthedPantryRoute
  '/places': typeof AuthedPlacesRoute
  '/join/$code': typeof JoinCodeRoute
  '/': typeof AuthedIndexRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/appearance': typeof AuthedSettingsAppearanceRoute
  '/settings/devices': typeof AuthedSettingsDevicesRoute
  '/settings/household': typeof AuthedSettingsHouseholdRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/body': typeof AuthedBodyRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/fleet': typeof AuthedFleetRoute
  '/_authed/lists': typeof AuthedListsRoute
  '/_authed/money': typeof AuthedMoneyRoute
  '/_authed/notes': typeof AuthedNotesRoute
  '/_authed/pantry': typeof AuthedPantryRoute
  '/_authed/places': typeof AuthedPlacesRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/join/$code': typeof JoinCodeRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/settings/account': typeof AuthedSettingsAccountRoute
  '/_authed/settings/appearance': typeof AuthedSettingsAppearanceRoute
  '/_authed/settings/devices': typeof AuthedSettingsDevicesRoute
  '/_authed/settings/household': typeof AuthedSettingsHouseholdRoute
  '/_authed/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/body'
    | '/calendar'
    | '/fleet'
    | '/lists'
    | '/money'
    | '/notes'
    | '/pantry'
    | '/places'
    | '/settings'
    | '/join/$code'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/devices'
    | '/settings/household'
    | '/settings/notifications'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/body'
    | '/calendar'
    | '/fleet'
    | '/lists'
    | '/money'
    | '/notes'
    | '/pantry'
    | '/places'
    | '/join/$code'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/devices'
    | '/settings/household'
    | '/settings/notifications'
    | '/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/body'
    | '/_authed/calendar'
    | '/_authed/fleet'
    | '/_authed/lists'
    | '/_authed/money'
    | '/_authed/notes'
    | '/_authed/pantry'
    | '/_authed/places'
    | '/_authed/settings'
    | '/join/$code'
    | '/_authed/'
    | '/_authed/settings/account'
    | '/_authed/settings/appearance'
    | '/_authed/settings/devices'
    | '/_authed/settings/household'
    | '/_authed/settings/notifications'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/body': {
      id: '/_authed/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AuthedBodyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/fleet': {
      id: '/_authed/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthedFleetRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/lists': {
      id: '/_authed/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AuthedListsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/money': {
      id: '/_authed/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthedMoneyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notes': {
      id: '/_authed/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pantry': {
      id: '/_authed/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthedPantryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/places': {
      id: '/_authed/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AuthedPlacesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/account': {
      id: '/_authed/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthedSettingsAccountRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/appearance': {
      id: '/_authed/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthedSettingsAppearanceRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/devices': {
      id: '/_authed/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof AuthedSettingsDevicesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/household': {
      id: '/_authed/settings/household'
      path: '/household'
      fullPath: '/settings/household'
      preLoaderRoute: typeof AuthedSettingsHouseholdRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/notifications': {
      id: '/_authed/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsAccountRoute: typeof AuthedSettingsAccountRoute
  AuthedSettingsAppearanceRoute: typeof AuthedSettingsAppearanceRoute
  AuthedSettingsDevicesRoute: typeof AuthedSettingsDevicesRoute
  AuthedSettingsHouseholdRoute: typeof AuthedSettingsHouseholdRoute
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAccountRoute: AuthedSettingsAccountRoute,
  AuthedSettingsAppearanceRoute: AuthedSettingsAppearanceRoute,
  AuthedSettingsDevicesRoute: AuthedSettingsDevicesRoute,
  AuthedSettingsHouseholdRoute: AuthedSettingsHouseholdRoute,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedBodyRoute: typeof AuthedBodyRoute
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedFleetRoute: typeof AuthedFleetRoute
  AuthedListsRoute: typeof AuthedListsRoute
  AuthedMoneyRoute: typeof AuthedMoneyRoute
  AuthedNotesRoute: typeof AuthedNotesRoute
  AuthedPantryRoute: typeof AuthedPantryRoute
  AuthedPlacesRoute: typeof AuthedPlacesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBodyRoute: AuthedBodyRoute,
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedFleetRoute: AuthedFleetRoute,
  AuthedListsRoute: AuthedListsRoute,
  AuthedMoneyRoute: AuthedMoneyRoute,
  AuthedNotesRoute: AuthedNotesRoute,
  AuthedPantryRoute: AuthedPantryRoute,
  AuthedPlacesRoute: AuthedPlacesRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
