/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedBodyRouteImport } from './routes/_authed.body'
import { Route as AuthedCalendarRouteImport } from './routes/_authed.calendar'
import { Route as AuthedFleetRouteImport } from './routes/_authed.fleet'
import { Route as AuthedListsRouteImport } from './routes/_authed.lists'
import { Route as AuthedMoneyRouteImport } from './routes/_authed.money'
import { Route as AuthedNotesRouteImport } from './routes/_authed.notes'
import { Route as AuthedPantryRouteImport } from './routes/_authed.pantry'
import { Route as AuthedPlacesRouteImport } from './routes/_authed.places'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBodyRoute = AuthedBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFleetRoute = AuthedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedListsRoute = AuthedListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMoneyRoute = AuthedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotesRoute = AuthedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPantryRoute = AuthedPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlacesRoute = AuthedPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/body': typeof AuthedBodyRoute
  '/calendar': typeof AuthedCalendarRoute
  '/fleet': typeof AuthedFleetRoute
  '/lists': typeof AuthedListsRoute
  '/money': typeof AuthedMoneyRoute
  '/notes': typeof AuthedNotesRoute
  '/pantry': typeof AuthedPantryRoute
  '/places': typeof AuthedPlacesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/body': typeof AuthedBodyRoute
  '/calendar': typeof AuthedCalendarRoute
  '/fleet': typeof AuthedFleetRoute
  '/lists': typeof AuthedListsRoute
  '/money': typeof AuthedMoneyRoute
  '/notes': typeof AuthedNotesRoute
  '/pantry': typeof AuthedPantryRoute
  '/places': typeof AuthedPlacesRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/body': typeof AuthedBodyRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/fleet': typeof AuthedFleetRoute
  '/_authed/lists': typeof AuthedListsRoute
  '/_authed/money': typeof AuthedMoneyRoute
  '/_authed/notes': typeof AuthedNotesRoute
  '/_authed/pantry': typeof AuthedPantryRoute
  '/_authed/places': typeof AuthedPlacesRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/body'
    | '/calendar'
    | '/fleet'
    | '/lists'
    | '/money'
    | '/notes'
    | '/pantry'
    | '/places'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/body'
    | '/calendar'
    | '/fleet'
    | '/lists'
    | '/money'
    | '/notes'
    | '/pantry'
    | '/places'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/body'
    | '/_authed/calendar'
    | '/_authed/fleet'
    | '/_authed/lists'
    | '/_authed/money'
    | '/_authed/notes'
    | '/_authed/pantry'
    | '/_authed/places'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/body': {
      id: '/_authed/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AuthedBodyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/fleet': {
      id: '/_authed/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthedFleetRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/lists': {
      id: '/_authed/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AuthedListsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/money': {
      id: '/_authed/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthedMoneyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notes': {
      id: '/_authed/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pantry': {
      id: '/_authed/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthedPantryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/places': {
      id: '/_authed/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AuthedPlacesRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBodyRoute: typeof AuthedBodyRoute
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedFleetRoute: typeof AuthedFleetRoute
  AuthedListsRoute: typeof AuthedListsRoute
  AuthedMoneyRoute: typeof AuthedMoneyRoute
  AuthedNotesRoute: typeof AuthedNotesRoute
  AuthedPantryRoute: typeof AuthedPantryRoute
  AuthedPlacesRoute: typeof AuthedPlacesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBodyRoute: AuthedBodyRoute,
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedFleetRoute: AuthedFleetRoute,
  AuthedListsRoute: AuthedListsRoute,
  AuthedMoneyRoute: AuthedMoneyRoute,
  AuthedNotesRoute: AuthedNotesRoute,
  AuthedPantryRoute: AuthedPantryRoute,
  AuthedPlacesRoute: AuthedPlacesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
