-- GENERATED by tools/gate_corpus_sql.py from app/src/test/resources/gate-corpus.json.
-- Do not edit here; edit the corpus and regenerate, or the two sides stop sharing a source.
--
-- Ends in a deliberate RAISE so the whole transaction rolls back. Nothing survives.
do $$
declare
  r jsonb;
  actual text;
  failures text := '';
  checked integer := 0;
begin

  -- ledger: valid three-anchor statement commits
  r := public.commit_statement('{"content_sha256": "corpus-ledger-0", "account_last4": "1234", "account_nickname": "corpus", "currency": "USD", "provenance": "DETERMINISTIC", "stated_total_cents": 149550, "opening_balance_cents": 500000, "closing_balance_cents": 649550, "lines": [{"txn_date": "2026-07-03", "description": "COFFEE", "amount_cents": -450, "line_ref": "corpus-0-0"}, {"txn_date": "2026-07-11", "description": "SALARY", "amount_cents": 300000, "line_ref": "corpus-0-1"}, {"txn_date": "2026-07-20", "description": "RENT", "amount_cents": -150000, "line_ref": "corpus-0-2"}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'COMMITTED' then
    failures := failures || E'\n  LEDGER valid three-anchor statement commits: expected COMMITTED, got ' || coalesce(actual, 'null');
  end if;

  -- ledger: empty extraction quarantines even when every figure is zero
  r := public.commit_statement('{"content_sha256": "corpus-ledger-1", "account_last4": "1234", "account_nickname": "corpus", "currency": "USD", "provenance": "DETERMINISTIC", "stated_total_cents": 0, "opening_balance_cents": 500000, "closing_balance_cents": 500000, "lines": []}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'QUARANTINED' then
    failures := failures || E'\n  LEDGER empty extraction quarantines even when every figure is zero: expected QUARANTINED, got ' || coalesce(actual, 'null');
  end if;

  -- ledger: lines that do not sum to the stated total quarantine
  r := public.commit_statement('{"content_sha256": "corpus-ledger-2", "account_last4": "1234", "account_nickname": "corpus", "currency": "USD", "provenance": "DETERMINISTIC", "stated_total_cents": 999, "opening_balance_cents": 500000, "closing_balance_cents": 649550, "lines": [{"txn_date": "2026-07-03", "description": "COFFEE", "amount_cents": -450, "line_ref": "corpus-2-0"}, {"txn_date": "2026-07-11", "description": "SALARY", "amount_cents": 300000, "line_ref": "corpus-2-1"}, {"txn_date": "2026-07-20", "description": "RENT", "amount_cents": -150000, "line_ref": "corpus-2-2"}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'QUARANTINED' then
    failures := failures || E'\n  LEDGER lines that do not sum to the stated total quarantine: expected QUARANTINED, got ' || coalesce(actual, 'null');
  end if;

  -- ledger: balance movement disagreeing with the line sum quarantines
  r := public.commit_statement('{"content_sha256": "corpus-ledger-3", "account_last4": "1234", "account_nickname": "corpus", "currency": "USD", "provenance": "DETERMINISTIC", "stated_total_cents": 149550, "opening_balance_cents": 500000, "closing_balance_cents": 1, "lines": [{"txn_date": "2026-07-03", "description": "COFFEE", "amount_cents": -450, "line_ref": "corpus-3-0"}, {"txn_date": "2026-07-11", "description": "SALARY", "amount_cents": 300000, "line_ref": "corpus-3-1"}, {"txn_date": "2026-07-20", "description": "RENT", "amount_cents": -150000, "line_ref": "corpus-3-2"}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'QUARANTINED' then
    failures := failures || E'\n  LEDGER balance movement disagreeing with the line sum quarantines: expected QUARANTINED, got ' || coalesce(actual, 'null');
  end if;

  -- ledger: a single line that ties out commits
  r := public.commit_statement('{"content_sha256": "corpus-ledger-4", "account_last4": "1234", "account_nickname": "corpus", "currency": "USD", "provenance": "DETERMINISTIC", "stated_total_cents": -899, "opening_balance_cents": 100000, "closing_balance_cents": 99101, "lines": [{"txn_date": "2026-06-10", "description": "VPN24.ME", "amount_cents": -899, "line_ref": "corpus-4-0"}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'COMMITTED' then
    failures := failures || E'\n  LEDGER a single line that ties out commits: expected COMMITTED, got ' || coalesce(actual, 'null');
  end if;

  -- ledger: a genuinely zero-movement month with a real line commits
  r := public.commit_statement('{"content_sha256": "corpus-ledger-5", "account_last4": "1234", "account_nickname": "corpus", "currency": "USD", "provenance": "DETERMINISTIC", "stated_total_cents": 0, "opening_balance_cents": 500000, "closing_balance_cents": 500000, "lines": [{"txn_date": "2026-07-05", "description": "CHARGE", "amount_cents": -2500, "line_ref": "corpus-5-0"}, {"txn_date": "2026-07-06", "description": "REFUND", "amount_cents": 2500, "line_ref": "corpus-5-1"}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'COMMITTED' then
    failures := failures || E'\n  LEDGER a genuinely zero-movement month with a real line commits: expected COMMITTED, got ' || coalesce(actual, 'null');
  end if;

  -- pantry: valid receipt with a printed subtotal commits
  r := public.commit_receipt('{"content_sha256": "corpus-pantry-0", "store": "CORPUS", "purchase_date": "2026-07-15", "currency": "SGD", "provenance": "LLM_RECONCILED", "total_cents": 1242, "subtotal_cents": 1150, "tax_cents": 92, "items": [{"name": "MILK", "quantity": 1, "total_price_cents": 450, "estimated_calories_kcal": 620}, {"name": "BREAD", "quantity": 2, "total_price_cents": 700}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'COMMITTED' then
    failures := failures || E'\n  PANTRY valid receipt with a printed subtotal commits: expected COMMITTED, got ' || coalesce(actual, 'null');
  end if;

  -- pantry: empty item list quarantines
  r := public.commit_receipt('{"content_sha256": "corpus-pantry-1", "store": "CORPUS", "purchase_date": "2026-07-15", "currency": "SGD", "provenance": "LLM_RECONCILED", "total_cents": 1242, "subtotal_cents": 1150, "tax_cents": 92, "items": []}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'QUARANTINED' then
    failures := failures || E'\n  PANTRY empty item list quarantines: expected QUARANTINED, got ' || coalesce(actual, 'null');
  end if;

  -- pantry: items not summing to the printed subtotal quarantines
  r := public.commit_receipt('{"content_sha256": "corpus-pantry-2", "store": "CORPUS", "purchase_date": "2026-07-15", "currency": "SGD", "provenance": "LLM_RECONCILED", "total_cents": 1392, "subtotal_cents": 1300, "tax_cents": 92, "items": [{"name": "MILK", "quantity": 1, "total_price_cents": 450}, {"name": "BREAD", "quantity": 2, "total_price_cents": 700}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'QUARANTINED' then
    failures := failures || E'\n  PANTRY items not summing to the printed subtotal quarantines: expected QUARANTINED, got ' || coalesce(actual, 'null');
  end if;

  -- pantry: subtotal plus tax not reaching the printed total quarantines
  r := public.commit_receipt('{"content_sha256": "corpus-pantry-3", "store": "CORPUS", "purchase_date": "2026-07-15", "currency": "SGD", "provenance": "LLM_RECONCILED", "total_cents": 9999, "subtotal_cents": 1150, "tax_cents": 92, "items": [{"name": "MILK", "quantity": 1, "total_price_cents": 450}, {"name": "BREAD", "quantity": 2, "total_price_cents": 700}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'QUARANTINED' then
    failures := failures || E'\n  PANTRY subtotal plus tax not reaching the printed total quarantines: expected QUARANTINED, got ' || coalesce(actual, 'null');
  end if;

  -- pantry: no printed subtotal, figures tie, commits
  r := public.commit_receipt('{"content_sha256": "corpus-pantry-4", "store": "CORPUS", "purchase_date": "2026-07-15", "currency": "SGD", "provenance": "LLM_RECONCILED", "total_cents": 1242, "subtotal_cents": null, "tax_cents": 92, "items": [{"name": "MILK", "quantity": 1, "total_price_cents": 450}, {"name": "BREAD", "quantity": 2, "total_price_cents": 700}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'COMMITTED' then
    failures := failures || E'\n  PANTRY no printed subtotal, figures tie, commits: expected COMMITTED, got ' || coalesce(actual, 'null');
  end if;

  -- pantry: no printed subtotal, figures do not tie, quarantines
  r := public.commit_receipt('{"content_sha256": "corpus-pantry-5", "store": "CORPUS", "purchase_date": "2026-07-15", "currency": "SGD", "provenance": "LLM_RECONCILED", "total_cents": 1, "subtotal_cents": null, "tax_cents": 92, "items": [{"name": "MILK", "quantity": 1, "total_price_cents": 450}, {"name": "BREAD", "quantity": 2, "total_price_cents": 700}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'QUARANTINED' then
    failures := failures || E'\n  PANTRY no printed subtotal, figures do not tie, quarantines: expected QUARANTINED, got ' || coalesce(actual, 'null');
  end if;

  -- pantry: macro estimates never affect the gate
  r := public.commit_receipt('{"content_sha256": "corpus-pantry-6", "store": "CORPUS", "purchase_date": "2026-07-15", "currency": "SGD", "provenance": "LLM_RECONCILED", "total_cents": 1242, "subtotal_cents": 1150, "tax_cents": 92, "items": [{"name": "MILK", "quantity": 1, "total_price_cents": 450, "estimated_calories_kcal": 999999, "estimated_protein_g": 4242}, {"name": "BREAD", "quantity": 2, "total_price_cents": 700, "estimated_calories_kcal": -1}]}'::jsonb);
  actual := r ->> 'outcome';
  checked := checked + 1;
  if actual <> 'COMMITTED' then
    failures := failures || E'\n  PANTRY macro estimates never affect the gate: expected COMMITTED, got ' || coalesce(actual, 'null');
  end if;

  if failures = '' then
    raise exception E'GATE CORPUS: all % cases agree. (rolled back)', checked;
  else
    raise exception E'GATE CORPUS: % cases checked, MISMATCHES:%', checked, failures;
  end if;
end $$;
