"""MCP server over the LEGION ticket board, read-only.

Two sources, both already in the repo:

- `docs/board.json`, generated by tools/pending_wiki.py from ticket frontmatter. It lists every
  OPEN ticket per map with its ready / built / blocked state. It is a generated file, so it can
  lag the tickets; every result carries `board_stale` when a ticket file is newer than the JSON,
  and the fix is `python tools/pending_wiki.py`, not editing the JSON.
- The ticket markdown under `.scratch/<map>/issues/NN-*.md` and each map's `map.md`. `ticket()`
  reads the file itself, so it is current even when the board is stale.

Some tickets carry no `ticket:` or `title:` in their frontmatter, so board.json shows them with
an empty number and title. This server fills both from the filename prefix and the first `#`
heading, and says when it did.

Nothing here writes. Ticket status changes are edits to the ticket file, then a re-run of the
sync scripts (CLAUDE.md section 12).

    uv run --project tools/mcp/board tools/mcp/board/server.py
"""
import glob
import json
import os
import re

from mcp.server.fastmcp import FastMCP

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
BOARD_JSON = os.path.join(ROOT, "docs", "board.json")
SCRATCH = os.path.join(ROOT, ".scratch")

mcp = FastMCP("legion-board")


def _frontmatter(path: str) -> tuple[dict, str]:
    """Splits a ticket into (frontmatter dict, body). Mirrors tools/pending_wiki.py's parser."""
    text = open(path, encoding="utf-8-sig").read()
    if not text.startswith("---\n"):
        return {}, text
    head, _, body = text.partition("\n---\n")
    out = {}
    for line in head.split("\n"):
        m = re.match(r"^([a-z_-]+):\s*(.*)$", line)
        if m:
            out[m.group(1)] = m.group(2).strip().strip('"')
    return out, body


def _heading(body: str) -> str:
    for line in body.split("\n"):
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def _ticket_files(map_slug: str) -> list[str]:
    return sorted(glob.glob(os.path.join(SCRATCH, map_slug, "issues", "*.md")))


def _num_from_name(path: str) -> str:
    m = re.match(r"^(\d+)", os.path.basename(path))
    return m.group(1) if m else ""


def _index_map(map_slug: str) -> list[dict]:
    """Every ticket file in a map, in filename order (the order pending_wiki.py uses), with
    num/title filled from the file when the frontmatter lacks them. A list, not a dict: two
    files can share a number (backend-erp has two 06s), and both must survive."""
    rows: list[dict] = []
    for path in _ticket_files(map_slug):
        fm, body = _frontmatter(path)
        num = fm.get("ticket") or _num_from_name(path)
        title = fm.get("title") or _heading(body)
        rows.append({
            "num": num, "title": title, "path": os.path.relpath(path, ROOT).replace("\\", "/"),
            "type": fm.get("type", "task"), "status": fm.get("status", "open"),
            "detail": fm.get("status-detail", ""),
            "filled_from_file": not (fm.get("ticket") and fm.get("title")),
        })
    return rows


DONE = {"resolved", "closed", "killed", "archived", "graduated", "fixed", "superseded"}


def _load_board() -> dict:
    if not os.path.isfile(BOARD_JSON):
        return {"error": "docs/board.json is missing; run `python tools/pending_wiki.py`"}
    board = json.load(open(BOARD_JSON, encoding="utf-8"))
    board_mtime = os.path.getmtime(BOARD_JSON)
    newest = 0.0
    for path in glob.glob(os.path.join(SCRATCH, "*", "issues", "*.md")) + glob.glob(os.path.join(SCRATCH, "*", "map.md")):
        newest = max(newest, os.path.getmtime(path))
    board["board_stale"] = newest > board_mtime
    if board["board_stale"]:
        board["stale_hint"] = "a ticket or map file is newer than docs/board.json; run `python tools/pending_wiki.py`"
    return board


def _fill(board: dict) -> dict:
    """Fills empty num/title in board.json rows from the ticket files, matching by position.

    board.json lists a map's tickets in filename order (pending_wiki.py sorts the glob), so the
    Nth open ticket in board.json is the Nth open ticket file. Rows already carrying a number are
    matched by number instead.
    """
    for m in board.get("maps", []):
        open_files = [t for t in _index_map(m["slug"]) if t["status"] not in DONE]
        for pos, row in enumerate(m.get("tickets", [])):
            src = None
            if row.get("num"):
                src = next((t for t in open_files if t["num"].zfill(2) == row["num"].zfill(2)), None)
            elif pos < len(open_files):
                src = open_files[pos]
            if src is None:
                continue
            row.setdefault("path", src["path"])
            if not row.get("num"):
                row["num"] = src["num"]
                row["num_from_file"] = True
            if not row.get("title"):
                row["title"] = src["title"]
                row["title_from_file"] = True
            row["map"] = m["slug"]
    return board


def _flatten(board: dict, keep) -> list[dict]:
    out = []
    for m in board.get("maps", []):
        for t in m.get("tickets", []):
            if keep(t):
                out.append({k: t.get(k) for k in ("map", "num", "title", "type", "status", "detail", "blocked_by", "path")})
    return out


@mcp.tool()
def ready() -> dict:
    """Open tickets with every blocker resolved, not parked, still owing code. Read-only.

    CLAUDE.md section 12: anything READY is built, not parked. Reads docs/board.json; the result
    flags `board_stale` when a ticket file is newer than the JSON.
    """
    board = _load_board()
    if "error" in board:
        return board
    _fill(board)
    rows = _flatten(board, lambda t: t.get("ready") and t.get("status") not in ("built", "kiv"))
    return {"count": len(rows), "tickets": rows, "totals": board.get("totals"),
            "generated_at": board.get("generated_at"), "board_stale": board["board_stale"],
            "hint": board.get("stale_hint")}


@mcp.tool()
def blocked() -> dict:
    """Open tickets that name at least one unresolved blocker. Read-only.

    Each row carries `blocked_by`, the ticket numbers within the same map that must resolve
    first. Reads docs/board.json.
    """
    board = _load_board()
    if "error" in board:
        return board
    _fill(board)
    rows = _flatten(board, lambda t: bool(t.get("blocked_by")) and t.get("status") not in ("built", "kiv"))
    return {"count": len(rows), "tickets": rows, "generated_at": board.get("generated_at"),
            "board_stale": board["board_stale"], "hint": board.get("stale_hint")}


@mcp.tool()
def ticket(map: str, number: str) -> dict:
    """One ticket in full: frontmatter and markdown body, read from the file itself. Read-only.

    `map` is the .scratch/ directory slug (`backend-erp`), `number` the ticket number (`3` or
    `03`). Current even when docs/board.json is stale, because it reads the markdown directly.
    Returns an error naming what exists when the ticket is not found.
    """
    slug = map.strip().strip("/")
    issues = os.path.join(SCRATCH, slug, "issues")
    if not os.path.isdir(issues):
        maps = sorted(os.path.basename(p) for p in glob.glob(os.path.join(SCRATCH, "*")) if os.path.isdir(p))
        return {"found": False, "error": "no map %r under .scratch/" % slug, "maps": maps}
    want = str(number).strip().zfill(2)
    matches = [p for p in _ticket_files(slug) if _num_from_name(p).zfill(2) == want]
    if not matches:
        have = sorted({_num_from_name(p) for p in _ticket_files(slug)})
        return {"found": False, "error": "no ticket %s in %s" % (want, slug), "numbers": have}
    result = {"found": True, "map": slug, "number": want, "files": []}
    for path in matches:
        fm, body = _frontmatter(path)
        result["files"].append({
            "path": os.path.relpath(path, ROOT).replace("\\", "/"),
            "frontmatter": fm,
            "title": fm.get("title") or _heading(body),
            "body": body.strip(),
        })
    if len(matches) > 1:
        result["note"] = "%d files share number %s in this map; all are returned" % (len(matches), want)
    return result


@mcp.tool()
def map(name: str) -> dict:
    """One map: its board.json summary, its map.md frontmatter and body, and every ticket file. Read-only.

    `name` is the .scratch/ slug. Tickets come from the files so resolved ones are listed too,
    with their status; the board.json block covers only the open ones.
    """
    slug = name.strip().strip("/")
    map_dir = os.path.join(SCRATCH, slug)
    if not os.path.isdir(map_dir):
        maps = sorted(os.path.basename(p) for p in glob.glob(os.path.join(SCRATCH, "*")) if os.path.isdir(p))
        return {"found": False, "error": "no map %r under .scratch/" % slug, "maps": maps}
    board = _load_board()
    summary = None
    if "error" not in board:
        _fill(board)
        summary = next((m for m in board["maps"] if m["slug"] == slug), None)
    map_md = os.path.join(map_dir, "map.md")
    map_fm, map_body = _frontmatter(map_md) if os.path.isfile(map_md) else ({}, "")
    tickets = _index_map(slug)
    return {
        "found": True, "map": slug,
        "title": map_fm.get("title") or _heading(map_body) or slug,
        "map_frontmatter": map_fm, "map_body": map_body.strip(),
        "tickets": tickets, "ticket_count": len(tickets),
        "board": summary,
        "board_stale": board.get("board_stale"), "hint": board.get("stale_hint") or board.get("error"),
    }


if __name__ == "__main__":
    mcp.run()
