"""`public.assistant_companions` and `public.assistant_calls` (web-assistant ticket 07).

Generated by Django 5.2.7 on 2026-10-05, plus the temporary search_path swap
`engine_mcp/migrations/0001_initial.py` uses so both tables land in `public`
beside the other tenant tables `household.tenancy.TENANT_TABLES` lists (see
`assistant/models.py`). Born tenanted: `household` is a real ForeignKey, so
`household/migrations/0002`'s SQL loop has nothing to add. Nothing here
touches the `private` schema, which the live engine role cannot use.

ADDITIVE: two new tables, nothing existing touched.
"""

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models

_SWAP_SEARCH_PATH_TO_PUBLIC_FIRST = migrations.RunSQL(
    sql="SET search_path TO public, django;",
    reverse_sql="SET search_path TO django, public;",
)

_RESTORE_SEARCH_PATH_TO_DJANGO_FIRST = migrations.RunSQL(
    sql="SET search_path TO django, public;",
    reverse_sql="SET search_path TO public, django;",
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0004_devicetoken_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        _SWAP_SEARCH_PATH_TO_PUBLIC_FIRST,
        migrations.CreateModel(
            name='AssistantCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.TextField(choices=[('session', 'Token mint'), ('tool', 'Tool call')])),
                ('tool', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(choices=[('ok', 'OK'), ('refused', 'Refused'), ('failed', 'Failed'), ('throttled', 'Throttled')])),
                ('at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='household.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_calls',
                'indexes': [models.Index(fields=['household', '-at'], name='assistant_calls_household_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['ok', 'refused', 'failed', 'throttled'])), name='assistant_calls_outcome_valid'), models.CheckConstraint(condition=models.Q(('kind__in', ['session', 'tool'])), name='assistant_calls_kind_valid')],
            },
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('persona_key', models.TextField(default='alfred')),
                ('persona_fragment', models.TextField(blank=True, default='')),
                ('voice_name', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='household.household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_companions',
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='assistant_companions_name_not_blank')],
            },
        ),
        _RESTORE_SEARCH_PATH_TO_DJANGO_FIRST,
    ]
