package com.kevin.legion.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A nightly foresight note generated by a Gemini Flash one-shot sub-agent.
 * The agent receives a compact JSON summary of recent obd_samples aggregates
 * and oil_analyses and writes a natural-language risk observation persisted here.
 *
 * Framing rule: never "AI predicts" — the mascot *notices*
 * ("coolant runs 6°F hotter this month…"). Costs ride the user's own key.
 *
 * pidsJson: JSON object of the PID aggregates the agent was given, kept for
 * reproducibility / debugging (not surfaced to the driver).
 */
@Entity(tableName = "foresight_notes")
data class ForesightNote(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val vehicleId: String,
    val generatedAt: Long,
    val content: String,        // natural-language observation
    val pidsJson: String = "",  // input summary for debugging
    val dismissed: Boolean = false,
)
