package com.kevin.legion.data.local

import com.kevin.legion.testutil.RoomTestReset
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment

/**
 * DAO-level regression for [Goal]'s revision-trail read path (`.scratch/aspect-advisors/issues/
 * 02-goal-store.md`, answer call 4) - the shape the [GoalDao.currentGoals] query exists to get
 * right: a lineage with several revisions must read back as ONE current row, and closing it must
 * drop it out entirely, not just flip a flag the read path forgets to check.
 *
 * Tests mint each lineage with an explicit, arbitrary [Goal.lineageId] literal rather than
 * reusing Room's autogenerated [Goal.id] - the DAO is agnostic to whatever convention a real
 * caller settles on for choosing one, so pinning it to a fixed number keeps these tests from
 * accidentally depending on Room's id-assignment order.
 *
 * Robolectric through the real [CarDatabase.getDatabase] path, same shape as
 * [CarDatabaseFreshInstallTest] - see its doc comment for why a hand-rolled in-memory DB would not
 * exercise the same wiring.
 */
@RunWith(RobolectricTestRunner::class)
class GoalDaoTest {
    private val context = RuntimeEnvironment.getApplication()
    private val dao get() = CarDatabase.getDatabase(context).goalDao()

    @Before
    fun clearState() {
        RoomTestReset.resetCarDatabaseSingleton()
    }

    @Test
    fun `a lineage with three revisions returns only the newest from currentGoals`() = runBlocking {
        val lineageId = 42L
        val firstId = dao.insert(
            Goal(lineageId = lineageId, aspect = "bio", statement = "get to 190 lbs", targetValue = 190.0, unit = "lbs")
        )
        val secondId = dao.insert(
            Goal(
                lineageId = lineageId,
                aspect = "bio",
                statement = "get to 185 lbs",
                targetValue = 185.0,
                unit = "lbs",
                supersedesId = firstId,
            )
        )
        dao.insert(
            Goal(
                lineageId = lineageId,
                aspect = "bio",
                statement = "get to 180 lbs",
                targetValue = 180.0,
                unit = "lbs",
                supersedesId = secondId,
            )
        )

        val current = dao.currentGoals("bio")

        assertEquals("only the newest revision of the lineage should surface", 1, current.size)
        assertEquals("get to 180 lbs", current.single().statement)
        assertEquals(180.0, current.single().targetValue)

        val trail = dao.history(lineageId)
        assertEquals("nothing in the trail is deleted or overwritten", 3, trail.size)
    }

    @Test
    fun `a closed goal is excluded from currentGoals`() = runBlocking {
        val lineageId = 7L
        dao.insert(Goal(lineageId = lineageId, aspect = "fleet", statement = "sell the old car"))
        dao.close(lineageId, "achieved", System.currentTimeMillis())

        val current = dao.currentGoals("fleet")

        assertTrue("a closed lineage must not appear in currentGoals", current.isEmpty())

        val trail = dao.history(lineageId)
        assertEquals("the row itself must still exist, only its status changed", 1, trail.size)
        assertEquals("achieved", trail.single().status)
    }

    @Test
    fun `allCurrentGoals reads across every aspect in one call`() = runBlocking {
        dao.insert(Goal(lineageId = 1L, aspect = "bio", statement = "bio goal"))
        dao.insert(Goal(lineageId = 2L, aspect = "fleet", statement = "fleet goal"))
        dao.insert(Goal(lineageId = 3L, aspect = "cred", statement = "cred goal"))
        dao.close(3L, "abandoned", System.currentTimeMillis())

        val all = dao.allCurrentGoals()

        assertEquals("bio + fleet, cred excluded because it's closed", 2, all.size)
        assertTrue(all.any { it.aspect == "bio" })
        assertTrue(all.any { it.aspect == "fleet" })
        assertTrue("closed goals must not leak into the cross-aspect read", all.none { it.aspect == "cred" })
    }
}
