package com.kevin.legion.ledger.parsers

import com.kevin.legion.data.local.IngestMethod
import com.kevin.legion.data.local.LedgerCurrency
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import java.io.File
import java.time.Instant
import java.time.ZoneOffset

/**
 * Fixtures generated by `tools/make_ledger_fixture.py`'s `make_card_*`
 * functions - every figure here is transcribed from that script's own
 * stdout (`python tools/make_ledger_fixture.py`), never hand-derived twice.
 */
@RunWith(RobolectricTestRunner::class)
class BofaCardStatementParserTest {
    @Before
    fun setup() {
        PdfWords.init(RuntimeEnvironment.getApplication())
    }

    private fun fixture(name: String) = File("src/test/resources/ledger_fixtures/$name")

    @Test
    fun `parses a happy-path card statement across three sections plus an optional fourth`() {
        val fixture = fixture("bofa_card_happy_path.pdf")
        val transactions = fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }

        // 2 payments + 3 purchases + 1 interest row. The invented "Fees
        // Charged" section never prints a bare header on this fixture (see
        // BofaCardStatementParser's KDoc on why that's optional), and the
        // trap row after "Transactions Continued" must not appear here.
        assertEquals(6, transactions.size)
        assertTrue(transactions.all { it.ingestMethod == IngestMethod.DETERMINISTIC })
        assertTrue(transactions.all { it.currency == LedgerCurrency.USD })
        assertTrue(transactions.all { it.accountId == "5555555555557823" })
        assertFalse("the YTD trap row must never be ingested", transactions.any { it.amountCents == 99999L })

        // Signs are flipped from what the statement prints (Kevin's
        // 2026-08-07 decision, this file's own KDoc): a payment - money
        // Kevin did NOT lose - stores positive; a purchase or interest
        // charge - money that left - stores negative.
        assertEquals(150000L, transactions[0].amountCents)
        assertEquals(125550L, transactions[1].amountCents)
        assertEquals(-60000L, transactions[2].amountCents)
        assertEquals(-45025L, transactions[3].amountCents)
        assertEquals(-90000L, transactions[4].amountCents)
        assertEquals(-500L, transactions[5].amountCents)

        assertEquals("PAYMENT FROM CHK 5521 CONF#4mv2plq8h", transactions[0].description)
        assertEquals("NORTHWIND OUTFITTERS      Northwind.com/billWA", transactions[2].description)
    }

    /**
     * Kevin's 2026-08-07 decision, item 1: money leaving Kevin is negative on every account, not just
     * checking. The card's own paper prints the opposite convention (see this file's class KDoc), so
     * this asserts the STORED sign is normalised, independent of the happy-path test's exact literals.
     */
    @Test
    fun `card purchases store negative, payments store positive - money leaving Kevin is always negative`() {
        val fixture = fixture("bofa_card_happy_path.pdf")
        val transactions = fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }

        val payments = transactions.filter { it.description.startsWith("PAYMENT FROM") }
        val purchases = transactions.filter { !it.description.startsWith("PAYMENT FROM") }
        assertTrue("a payment is money Kevin didn't lose - stores positive", payments.isNotEmpty() && payments.all { it.amountCents > 0 })
        assertTrue("a purchase is money that left - stores negative", purchases.isNotEmpty() && purchases.all { it.amountCents < 0 })
    }

    @Test
    fun `rejects a card statement whose own section total is corrupted`() {
        val fixture = fixture("bofa_card_section_mismatch.pdf")
        val ex = assertThrows(BalanceContinuityException::class.java) {
            fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }
        }
        assertTrue(ex.userMessage!!.contains("Payments and Other Credits"))
        assertTrue(ex.userMessage!!.contains("Nothing was imported."))
    }

    @Test
    fun `rejects a card statement whose summary identity doesn't add up`() {
        val fixture = fixture("bofa_card_summary_mismatch.pdf")
        val ex = assertThrows(BalanceContinuityException::class.java) {
            fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }
        }
        assertTrue(ex.userMessage!!.contains("This statement's own summary doesn't add up"))
        assertTrue(ex.userMessage!!.contains("Nothing was imported."))
    }

    /**
     * The gate layer only a document-wide cross-check can catch: the
     * Payments SECTION's own printed total (layer 1) and the summary
     * identity (layer 2) both individually check out - the summary block's
     * "New Balance Total" was recomputed around the same corrupted
     * "Payments and Other Credits" figure - but the section's rows still
     * sum to the TRUE payments total, which no longer matches what the
     * summary claims the period's net movement is.
     */
    @Test
    fun `rejects a card statement that passes per-section and summary checks but fails the cross-check`() {
        val fixture = fixture("bofa_card_crosscheck_mismatch.pdf")
        val ex = assertThrows(BalanceContinuityException::class.java) {
            fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }
        }
        assertTrue(ex.userMessage!!.contains("net movement for the period"))
        assertTrue(ex.userMessage!!.contains("Nothing was imported."))
    }

    /**
     * The one case that silently corrupts a year of data if the
     * month-vs-period-start comparison is wrong: a December transaction on
     * a cycle whose printed year belongs to January must land in the
     * PRIOR year, and a January transaction must land in the printed year
     * itself.
     */
    @Test
    fun `derives the correct year across a December to January cycle boundary`() {
        val fixture = fixture("bofa_card_dec_jan_boundary.pdf")
        val transactions = fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }

        assertEquals(3, transactions.size)
        fun yearOf(epochMillis: Long) = Instant.ofEpochMilli(epochMillis).atZone(ZoneOffset.UTC).year

        // Signs flipped from what's printed (see this file's class KDoc): a
        // payment stores positive, a purchase stores negative.
        val decPayment = transactions.first { it.amountCents == 80000L }
        assertEquals(2026, yearOf(decPayment.txnDate))

        val decPurchase = transactions.first { it.amountCents == -15000L }
        assertEquals(2026, yearOf(decPurchase.txnDate))

        val janPurchase = transactions.first { it.amountCents == -22500L }
        assertEquals(2027, yearOf(janPurchase.txnDate))
    }

    /**
     * The real bug: Interest Charged rows carry no reference number and no
     * account number at all - `MM/DD MM/DD <description> <amount>` - and
     * this fixture's total is deliberately NONZERO (unlike the real
     * statement that first exposed the bug), because a zero total is
     * exactly what let the four dropped rows reconcile vacuously before.
     */
    @Test
    fun `parses bare-form Interest Charged rows with no reference or account number`() {
        val fixture = fixture("bofa_card_bare_interest_rows.pdf")
        val transactions = fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }

        // 2 payments + 3 purchases + 4 bare interest rows.
        assertEquals(9, transactions.size)
        val interestRows = transactions.filter { it.description.startsWith("INTEREST CHARGED") }
        assertEquals(4, interestRows.size)
        // Signs flipped from what's printed: interest charged is money that
        // left, so it stores negative (see this file's class KDoc).
        assertEquals(-815L, interestRows.sumOf { it.amountCents })
        assertEquals("INTEREST CHARGED ON PURCHASES", interestRows[0].description)
        assertEquals(-815L, interestRows[0].amountCents)
        assertEquals("INTEREST CHARGED ON BALANCE TRANSFERS", interestRows[1].description)
        assertEquals(0L, interestRows[1].amountCents)
    }

    /** Same bare-row shape, applied to Fees Charged - the ticket's "very likely the same shape" hypothesis. */
    @Test
    fun `parses bare-form Fees Charged rows with no reference or account number`() {
        val fixture = fixture("bofa_card_bare_fee_rows.pdf")
        val transactions = fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }

        assertEquals(6, transactions.size) // 2 payments + 3 purchases + 1 bare fee row
        val fee = transactions.first { it.description == "LATE FEE" }
        // Sign flipped from what's printed: a fee is money that left.
        assertEquals(-3500L, fee.amountCents)
    }

    /**
     * The vacuous-pass regression: a line inside a recognized section that
     * matches NEITHER row form must hard-fail the whole document, never
     * silently drop out while the section's $0.00 total "reconciles"
     * against zero real rows. This is the actual fix - the bare-row form
     * above only addresses the FIRST cause of the drop, not this one.
     */
    @Test
    fun `a line inside a section that matches no known row form quarantines rather than being skipped`() {
        val fixture = fixture("bofa_card_unparseable_row.pdf")
        val ex = assertThrows(GenericStatementParseException::class.java) {
            fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }
        }
        assertTrue(ex.userMessage!!.contains("doesn't look like a"))
        assertTrue(ex.userMessage!!.contains("Nothing was imported."))
    }

    @Test
    fun `a checking-account BofA statement is not claimed by the card parser`() {
        val fixture = fixture("bofa_happy_path.pdf")
        assertThrows(UnrecognizedLayoutException::class.java) {
            fixture.inputStream().use { BofaCardStatementParser.parse(fixture.name, it) }
        }
    }

    @Test
    fun `a card statement is not claimed by the checking parser`() {
        val fixture = fixture("bofa_card_happy_path.pdf")
        assertThrows(UnrecognizedLayoutException::class.java) {
            fixture.inputStream().use { BofaStatementParser.parse(fixture.name, it) }
        }
    }

    // Ticket 12 (2026-08-06): BofaCardCsvStatementParser stopped being a
    // named rejection and became a real parser producing UNRECONCILED rows -
    // its own tests, including the two that lived here, moved to
    // BofaCardCsvStatementParserTest.kt.
}
