package com.kevin.legion.ledger.parsers

import com.kevin.legion.data.local.IngestMethod
import com.kevin.legion.data.local.LedgerCurrency
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import java.io.File

@RunWith(RobolectricTestRunner::class)
class BofaStatementParserTest {
    @Before
    fun setup() {
        PdfWords.init(RuntimeEnvironment.getApplication())
    }

    @Test
    fun `parses a happy-path statement across all four sections`() {
        val fixture = File("src/test/resources/ledger_fixtures/bofa_happy_path.pdf")
        val transactions = fixture.inputStream().use { BofaStatementParser.parse(fixture.name, it) }.transactions

        assertEquals(4, transactions.size)
        assertEquals(200000L, transactions[0].amountCents)
        assertEquals("PAYROLL DEPOSIT", transactions[0].description)
        assertEquals(-10000L, transactions[1].amountCents)
        assertEquals(-5000L, transactions[2].amountCents)
        assertEquals(-1200L, transactions[3].amountCents)
        assertEquals(LedgerCurrency.USD, transactions[0].currency)
        assertEquals(IngestMethod.DETERMINISTIC, transactions[0].ingestMethod)
        assertEquals("123456789012", transactions[0].accountId)
    }

    /**
     * Ticket 12: this parser reconciles `beginningBalance + netTotal == endingBalance`
     * internally on every parse and used to throw both figures away - now they come back as this
     * statement's own printed opening/closing balance. `statedTotalCents` stays null: BofA prints
     * each SECTION's own total separately (see the four `assertEquals` above) and never one
     * combined figure for the whole statement - a real regression guard, since the fixture's own
     * lines sum to a nonzero net movement (183800), so a wrongly-reinstated `sum(amountCents)`
     * stand-in would fail this assertion with that number instead of null.
     */
    @Test
    fun `surfaces the printed beginning and ending balance but no single stated total`() {
        val fixture = File("src/test/resources/ledger_fixtures/bofa_happy_path.pdf")
        val parsed = fixture.inputStream().use { BofaStatementParser.parse(fixture.name, it) }

        assertEquals(null, parsed.anchors.statedTotalCents)
        assertEquals(false, parsed.anchors.hasAllThreeAnchors)
        // The beginning/ending balance are whatever the fixture states - not independently
        // re-typed here, since the parser's own internal check already ties them to the sum of
        // the four assertions above (200000 - 10000 - 5000 - 1200 = 183800 net movement).
        assertEquals(
            parsed.anchors.openingBalanceCents!! + 183800L,
            parsed.anchors.closingBalanceCents,
        )
    }

    @Test
    fun `rejects a statement with a corrupted section total`() {
        val fixture = File("src/test/resources/ledger_fixtures/bofa_section_mismatch.pdf")
        assertThrows(BalanceContinuityException::class.java) {
            fixture.inputStream().use { BofaStatementParser.parse(fixture.name, it) }
        }
    }

    /**
     * The real bug (Kevin's actual BofA statement, 2026-08-02): a wire's
     * description wraps three lines with a "Page 2 of 6" footer landing mid-
     * row, and the amount is alone on a fourth line. This fixture also has
     * an ordinary single-line row alongside it in the same section - the
     * regression case for "single-line rows still parse" lives here too,
     * plus the full statement's section totals and beginning+net=ending
     * balance check, generated by `tools/make_bofa_multiline_fixture.py`
     * from the same figures the parser itself will recompute, never typed
     * twice.
     */
    @Test
    fun `joins a multi-line wire row into one transaction and still reconciles`() {
        val fixture = File("src/test/resources/ledger_fixtures/bofa_multiline_wire.pdf")
        val transactions = fixture.inputStream().use { BofaStatementParser.parse(fixture.name, it) }.transactions

        assertEquals(5, transactions.size)

        val zelle = transactions[0]
        assertEquals(50000L, zelle.amountCents)
        assertEquals("Zelle payment from JANE DOE Conf# ab12cd34e", zelle.description)

        val wire = transactions[1]
        assertEquals(120000L, wire.amountCents)
        assertEquals(
            "WIRE TYPE:WIRE IN DATE: 260617 TIME:0802 ET TRN:2026061700277191 " +
                "SEQ:1002233445JS/100200 ORIG:ACME WIDGETS LLC ID:0099887766 SND BK:FIRST " +
                "NATIONAL BANK, N.A. ID:0002 PMT DET:MB60617135571826",
            wire.description,
        )
        // The "Page 2 of 6" footer interleaved between the wire's
        // continuation lines must not survive into the joined description.
        assertEquals(false, wire.description.contains("Page 2 of 6"))

        assertEquals(-4567L, transactions[2].amountCents)
        assertEquals(-2500L, transactions[3].amountCents)
        assertEquals(-1200L, transactions[4].amountCents)
        assertEquals(IngestMethod.DETERMINISTIC, wire.ingestMethod)
        assertEquals("987654321000", wire.accountId)
    }

    /**
     * The SECOND real bug found on Kevin's statement (2026-08-02), after the
     * multi-line wire fix above: every section name appears twice - once in
     * a front-page summary block, immediately followed by ITS OWN total
     * rather than a "Date ..." column header, and once as the real
     * transaction-table header. `extractSection` used to lock onto whichever
     * came first, which was always the summary line, so a section's body ran
     * straight through into the WRONG section's real rows. This fixture also
     * covers "Other subtractions" spanning a page break, with its header and
     * "Date ..." header reprinted and a reprinted account/name/date-range
     * line plus a "Page N of M" footer interleaved between the two halves of
     * its rows - both halves must land in one section with one total check.
     * Generated by `tools/make_bofa_multiline_fixture.py`'s
     * `make_summary_and_split_section_fixture`, totals derived
     * programmatically, never typed twice.
     */
    @Test
    fun `does not mistake the summary block for a section start and stitches a page-split section together`() {
        val fixture = File("src/test/resources/ledger_fixtures/bofa_summary_and_split_section.pdf")
        val transactions = fixture.inputStream().use { BofaStatementParser.parse(fixture.name, it) }.transactions

        assertEquals(6, transactions.size)

        // Deposits: single-line payroll row + the multi-line wire,
        // undisturbed by the summary block sitting above them in the text.
        assertEquals(300000L, transactions[0].amountCents)
        assertEquals(120000L, transactions[1].amountCents)

        // ATM: exactly its own one row - proof the summary block's
        // "Deposits and other additions" line never got treated as this
        // section's start (the old `indexOfFirst` bug's failure mode).
        assertEquals(-8000L, transactions[2].amountCents)

        // Other subtractions: both page-split pieces present as two rows in
        // one section, with the reprinted header/Date pair and the
        // interleaved account-line/page-footer furniture excluded from both.
        assertEquals(-3000L, transactions[3].amountCents)
        assertEquals(-4500L, transactions[4].amountCents)

        assertEquals(-1500L, transactions[5].amountCents)
    }

    @Test
    fun `a date-led row with no amount before the next date-led row still quarantines with a user message`() {
        val fixture = File("src/test/resources/ledger_fixtures/bofa_missing_amount.pdf")
        val thrown = assertThrows(GenericStatementParseException::class.java) {
            fixture.inputStream().use { BofaStatementParser.parse(fixture.name, it) }
        }
        assert(thrown.message?.contains("missing an amount") == true) {
            "expected a 'missing an amount' diagnostic, got: ${thrown.message}"
        }
        assert(thrown.userMessage != null) { "expected a userMessage, got null" }
    }
}
