package com.kevin.legion.ledger.parsers

import com.kevin.legion.data.local.IngestMethod
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import java.io.File

@RunWith(RobolectricTestRunner::class)
class DbsStatementParserTest {
    @Before
    fun setup() {
        PdfWords.init(RuntimeEnvironment.getApplication())
    }

    @Test
    fun `parses a happy-path statement with correct amounts and running balance`() {
        val fixture = File("src/test/resources/ledger_fixtures/dbs_happy_path.pdf")
        val transactions = fixture.inputStream().use { DbsStatementParser.parse(fixture.name, it) }

        assertEquals(3, transactions.size)
        assertEquals(-5000L, transactions[0].amountCents)
        assertEquals(295000L, transactions[1].balanceCents)
        assertEquals(IngestMethod.DETERMINISTIC, transactions[0].ingestMethod)
        assertEquals("1234567890", transactions[0].accountId)
        assertEquals("GROCERY STORE", transactions[0].description)
        assertEquals(200000L, transactions[1].amountCents)
        assertEquals(-5000L, transactions[2].amountCents)
        assertEquals(290000L, transactions[2].balanceCents)
    }

    @Test
    fun `rejects a statement with a corrupted closing balance`() {
        val fixture = File("src/test/resources/ledger_fixtures/dbs_balance_mismatch.pdf")
        assertThrows(BalanceContinuityException::class.java) {
            fixture.inputStream().use { DbsStatementParser.parse(fixture.name, it) }
        }
    }

    // Regression for the real DBS/POSB statement's description-pollution
    // bug: a rotated/sidebar watermark PdfBox emits as its own line, every
    // whitespace-separated token a single character, absorbed by the
    // multi-line description accumulator when it happened to fall between a
    // transaction row and the totals line. `dbs_description_artifact.pdf`
    // (generated by `tools/make_ledger_fixture.py`, all figures invented)
    // reproduces both the shape that hit Kevin's real file (an artifact line
    // immediately before "Total Balance Carried Forward:") and the shape the
    // bug report calls out as untested luck (an artifact line SANDWICHED
    // between two genuine continuation lines).
    @Test
    fun `skips an artifact line immediately before the closing totals`() {
        val fixture = File("src/test/resources/ledger_fixtures/dbs_description_artifact.pdf")
        val transactions = fixture.inputStream().use { DbsStatementParser.parse(fixture.name, it) }

        assertEquals(3, transactions.size)
        assertEquals("Interest Earned", transactions[2].description)
    }

    @Test
    fun `captures a legitimate multi-line description in full`() {
        val fixture = File("src/test/resources/ledger_fixtures/dbs_description_artifact.pdf")
        val transactions = fixture.inputStream().use { DbsStatementParser.parse(fixture.name, it) }

        // The full three-line description, artifact line excluded from the
        // middle of it (see the next test for that in isolation).
        assertEquals(
            "PAYMENT TO ACME SUPPLIES INVOICE REF 20260145 APPROVAL CODE 774411",
            transactions[0].description,
        )
    }

    @Test
    fun `an artifact line sandwiched between two continuation lines does not eat the second one`() {
        val fixture = File("src/test/resources/ledger_fixtures/dbs_description_artifact.pdf")
        val transactions = fixture.inputStream().use { DbsStatementParser.parse(fixture.name, it) }

        val description = transactions[0].description
        assertEquals(false, description.contains("1 4 8 A"))
        // The genuine continuation line AFTER the artifact must still land -
        // a fix that (wrongly) stopped accumulating entirely on any
        // non-matching line would drop this instead of just the artifact.
        assertEquals(true, description.contains("APPROVAL CODE 774411"))
    }
}
