package com.kevin.legion.ledger.parsers

import com.kevin.legion.data.local.IngestMethod
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import java.io.File

@RunWith(RobolectricTestRunner::class)
class StatementDispatcherTest {
    @Before
    fun setup() {
        PdfWords.init(RuntimeEnvironment.getApplication())
    }

    /**
     * `unrecognized_reconciling.pdf` (generated by `tools/make_ledger_fixture.py`)
     * is the only fixture that both falls through to the LLM AND can pass the
     * reconciliation gate - every other fallthrough fixture is built to fail,
     * which is why `IngestMethod.LLM_RECONCILED` had never been produced and
     * the ledger's "read by AI" label had never rendered.
     *
     * This test guards the half that can be checked offline: that it really
     * does fall through, and that the text a model would be handed still
     * carries the account line and the printed net movement it has to
     * reconcile against. The extraction itself is not tested here - that is a
     * billed network call on Kevin's own key (see the note in the fallthrough
     * test below).
     */
    @Test
    fun `the reconciling fixture falls through and carries the total the gate needs`() {
        val bytes = File("src/test/resources/ledger_fixtures/unrecognized_reconciling.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("unrecognized_reconciling.pdf", bytes)
        assertTrue("must reach the LLM path, not a deterministic parser", result is DeterministicResult.NeedsLlm)

        val text = (result as DeterministicResult.NeedsLlm).statementText
        // The account identifier and currency the agent needs to build a row.
        assertTrue("account reference missing from extracted text", text.contains("7781-224-9"))
        assertTrue("currency missing from extracted text", text.contains("USD"))
        // The stated total the gate reconciles against, and one line's amount.
        assertTrue("printed net movement missing", text.contains("Net movement for the period"))
        assertTrue("stated total missing", text.contains("1,025.00"))
        assertTrue("a transaction amount missing", text.contains("3,200.00"))

        // Guard the fallthrough itself: if either parser's recognition marker
        // ever appears here, this fixture silently stops testing the LLM path.
        assertFalse("would be claimed by DbsStatementParser", text.contains("Account No."))
        assertFalse("would be claimed by BofaStatementParser", text.contains("Account number"))
        assertFalse("would be claimed by BofaStatementParser", text.contains("Beginning balance on"))
    }

    @Test
    fun `recognized DBS layout succeeds via the deterministic path`() {
        val bytes = File("src/test/resources/ledger_fixtures/dbs_happy_path.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("dbs_happy_path.pdf", bytes)
        assertTrue(result is DeterministicResult.Success)
        val txns = (result as DeterministicResult.Success).transactions
        assertTrue(txns.all { it.ingestMethod == IngestMethod.DETERMINISTIC })
    }

    @Test
    fun `a recognized-but-corrupted DBS statement quarantines rather than falling to the LLM path`() {
        val bytes = File("src/test/resources/ledger_fixtures/dbs_balance_mismatch.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("dbs_balance_mismatch.pdf", bytes)
        assertTrue(result is DeterministicResult.Quarantined)
    }

    @Test
    fun `a matching accountHint does not disturb a PDF's own printed account`() {
        // The common case: the folder mapping agrees with what the file
        // itself states (or the folder is simply unmapped) - either way,
        // dbs_happy_path.pdf's own account (see DbsStatementParserTest) wins
        // and nothing is quarantined.
        val bytes = File("src/test/resources/ledger_fixtures/dbs_happy_path.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("dbs_happy_path.pdf", bytes, "1234567890")
        assertTrue(result is DeterministicResult.Success)
        assertTrue((result as DeterministicResult.Success).transactions.all { it.accountId == "1234567890" })
    }

    @Test
    fun `a folder mapping that disagrees with a PDF's own printed account is ignored, not quarantined`() {
        // dbs_happy_path.pdf prints account 1234567890 (DbsStatementParserTest).
        // A folder hint naming a DIFFERENT account no longer quarantines -
        // Kevin's real Drive layout mixes multiple accounts' files in one
        // subfolder on purpose (see StatementDispatcher.dispatchDeterministic's
        // doc comment), so a hint that happens to describe some OTHER file in
        // the same folder is simply irrelevant here. The document's own
        // stated account always wins.
        val bytes = File("src/test/resources/ledger_fixtures/dbs_happy_path.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("dbs_happy_path.pdf", bytes, "SOME-OTHER-ACCOUNT")
        assertTrue(result is DeterministicResult.Success)
        assertTrue((result as DeterministicResult.Success).transactions.all { it.accountId == "1234567890" })
    }

    @Test
    fun `Kevin's real layout - a checking PDF and a card PDF under the same accountHint each keep their own account`() {
        // The exact shape of USA Bank Statements/: one mapped folder holding
        // both a checking statement and a card statement, each printing a
        // DIFFERENT account of its own. Neither should be disturbed by the
        // shared folder-level hint, and neither should quarantine.
        val checkingBytes = File("src/test/resources/ledger_fixtures/bofa_happy_path.pdf").readBytes()
        val checkingResult = StatementDispatcher.dispatchDeterministic("bofa_happy_path.pdf", checkingBytes, "BOFA-CHECKING")
        assertTrue(checkingResult is DeterministicResult.Success)
        val checkingTxns = (checkingResult as DeterministicResult.Success).transactions
        assertTrue(checkingTxns.isNotEmpty())
        // 123456789012 per BofaStatementParserTest - its own printed account,
        // NOT the "BOFA-CHECKING" hint, proving the hint was never even
        // consulted for a file that states its own account.
        assertTrue(checkingTxns.all { it.accountId == "123456789012" })

        val cardBytes = File("src/test/resources/ledger_fixtures/bofa_card_happy_path.pdf").readBytes()
        val cardResult = StatementDispatcher.dispatchDeterministic("bofa_card_happy_path.pdf", cardBytes, "BOFA-CHECKING")
        assertTrue(cardResult is DeterministicResult.Success)
        val cardTxns = (cardResult as DeterministicResult.Success).transactions
        // 5555555555557823 per this file's own happy-path test above - a
        // DIFFERENT account than the checking PDF's, sharing the same
        // "BOFA-CHECKING" folder hint, and neither one quarantined.
        assertTrue(cardTxns.all { it.accountId == "5555555555557823" })
    }

    @Test
    fun `a folder-mapped CSV resolves through the dispatcher without a mismatch`() {
        val bytes = File("src/test/resources/ledger_fixtures/bofa_csv_happy_path.csv").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("bofa_csv_happy_path.csv", bytes, "BOFA-CHECKING")
        assertTrue(result is DeterministicResult.Success)
        assertTrue((result as DeterministicResult.Success).transactions.all { it.accountId == "BOFA-CHECKING" })
    }

    @Test
    fun `a CSV with no account reports NeedsAccount, not a quarantine`() {
        // Changed 2026-08-07. It used to assert Quarantined carrying the
        // parser's "Map the folder..." wording, which forced every caller to
        // repeat that instruction - including the single-file pick path, where
        // there IS no folder and the advice was impossible to follow. The
        // distinction is now typed: the numbers reconciled and only the account
        // is unknown, so each caller supplies wording that fits how the file
        // arrived.
        val bytes = File("src/test/resources/ledger_fixtures/bofa_csv_happy_path.csv").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("bofa_csv_happy_path.csv", bytes, null)
        assertTrue(result is DeterministicResult.NeedsAccount)
    }

    @Test
    fun `the same CSV parses cleanly once an account is supplied`() {
        // The other half of the above: NeedsAccount must mean "ask and retry",
        // not "this file is broken". Pins that the retry actually succeeds.
        val bytes = File("src/test/resources/ledger_fixtures/bofa_csv_happy_path.csv").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("bofa_csv_happy_path.csv", bytes, "BOFA-CHECKING")
        assertTrue(result is DeterministicResult.Success)
        assertTrue((result as DeterministicResult.Success).transactions.all { it.accountId == "BOFA-CHECKING" })
    }

    @Test
    fun `bytes that are neither a recognized CSV nor a real PDF quarantine instead of crashing PdfBox`() {
        // The exact hazard widening acceptance to CSV introduced: a file
        // that passed IngestPipeline.isAcceptableStatementFile's extension
        // gate (a .csv that ISN'T BofA's layout) must never reach
        // PDDocument.load() with non-PDF bytes.
        val garbage = "not,a,recognized,csv,layout\n1,2,3,4,5\n".toByteArray()
        val result = StatementDispatcher.dispatchDeterministic("mystery.csv", garbage)
        assertTrue(result is DeterministicResult.Quarantined)
        assertTrue((result as DeterministicResult.Quarantined).reason.contains("Nothing was imported."))
    }

    @Test
    fun `a happy-path card statement resolves through the dispatcher as DETERMINISTIC`() {
        val bytes = File("src/test/resources/ledger_fixtures/bofa_card_happy_path.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("bofa_card_happy_path.pdf", bytes)
        assertTrue(result is DeterministicResult.Success)
        val txns = (result as DeterministicResult.Success).transactions
        assertEquals(6, txns.size)
        assertTrue(txns.all { it.ingestMethod == IngestMethod.DETERMINISTIC })
        assertTrue(txns.all { it.accountId == "5555555555557823" })
    }

    /** Test 11: card CSV bytes -> DeterministicResult.Success, not Quarantined. */
    @Test
    fun `the card's mid-cycle CSV export succeeds as UNRECONCILED, not quarantined`() {
        // Ticket 12 (2026-08-06): BofaCardCsvStatementParser stopped being a
        // named rejection. This fixture (invented rows, see
        // tools/make_ledger_fixture.py) now commits as a real, if
        // unverified, import instead of quarantining.
        val bytes = File("src/test/resources/ledger_fixtures/currentTransaction_7823.csv").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("currentTransaction_7823.csv", bytes)
        assertTrue(result is DeterministicResult.Success)
        val txns = (result as DeterministicResult.Success).transactions
        assertTrue(txns.isNotEmpty())
        assertTrue(txns.all { it.ingestMethod == com.kevin.legion.data.local.IngestMethod.UNRECONCILED })
        assertTrue(txns.all { it.accountId == "7823" })
    }

    /** Test 12: checking CSV bytes still route to BofaCsvStatementParser (no shadowing, either direction). */
    @Test
    fun `checking CSV bytes still route to BofaCsvStatementParser, not the card CSV parser`() {
        val bytes = File("src/test/resources/ledger_fixtures/bofa_csv_happy_path.csv").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("bofa_csv_happy_path.csv", bytes, "BOFA-CHECKING")
        assertTrue(result is DeterministicResult.Success)
        val txns = (result as DeterministicResult.Success).transactions
        assertTrue(txns.all { it.ingestMethod == IngestMethod.DETERMINISTIC })
        assertTrue(txns.all { it.accountId == "BOFA-CHECKING" })
    }

    /** Test 13: real PDF bytes still reach the PDF parsers untouched. */
    @Test
    fun `real PDF bytes still reach the PDF parsers, untouched by either CSV parser`() {
        val bytes = File("src/test/resources/ledger_fixtures/dbs_happy_path.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("dbs_happy_path.pdf", bytes)
        assertTrue(result is DeterministicResult.Success)
        assertTrue((result as DeterministicResult.Success).transactions.all { it.ingestMethod == IngestMethod.DETERMINISTIC })
    }

    @Test
    fun `an unrecognized layout falls through to NeedsLlm without crashing, never quietly succeeding`() {
        // dispatchDeterministic never touches Gemini (that's the whole point
        // of the split - see StatementDispatcher's doc comment) - both
        // deterministic parsers correctly decline this layout and it comes
        // back NeedsLlm, carrying the already-extracted text.
        val bytes = File("src/test/resources/ledger_fixtures/unrecognized_layout.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("unrecognized_layout.pdf", bytes)
        assertTrue(result is DeterministicResult.NeedsLlm)
        assertTrue((result as DeterministicResult.NeedsLlm).statementText.isNotBlank())
        // Deliberately NOT exercising StatementDispatcher.runLlm here - it
        // makes a real HTTP call to the Gemini endpoint, which this repo's
        // rule is to never do from a test (every reachable call bills
        // Kevin's own key, even a request that later fails). runLlm's
        // graceful-failure behavior on a bad/missing key or no network is
        // exercised at the SubAgent.askWithUsage level instead (same
        // try/catch/HttpOutcome shape as the already-tested ask()).
    }
}
