package com.kevin.legion.ledger.parsers

import com.kevin.legion.data.local.IngestMethod
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import java.io.File

@RunWith(RobolectricTestRunner::class)
class StatementDispatcherTest {
    @Before
    fun setup() {
        PdfWords.init(RuntimeEnvironment.getApplication())
    }

    /**
     * `unrecognized_reconciling.pdf` (generated by `tools/make_ledger_fixture.py`)
     * is the only fixture that both falls through to the LLM AND can pass the
     * reconciliation gate - every other fallthrough fixture is built to fail,
     * which is why `IngestMethod.LLM_RECONCILED` had never been produced and
     * the ledger's "read by AI" label had never rendered.
     *
     * This test guards the half that can be checked offline: that it really
     * does fall through, and that the text a model would be handed still
     * carries the account line and the printed net movement it has to
     * reconcile against. The extraction itself is not tested here - that is a
     * billed network call on Kevin's own key (see the note in the fallthrough
     * test below).
     */
    @Test
    fun `the reconciling fixture falls through and carries the total the gate needs`() {
        val bytes = File("src/test/resources/ledger_fixtures/unrecognized_reconciling.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("unrecognized_reconciling.pdf", bytes)
        assertTrue("must reach the LLM path, not a deterministic parser", result is DeterministicResult.NeedsLlm)

        val text = (result as DeterministicResult.NeedsLlm).statementText
        // The account identifier and currency the agent needs to build a row.
        assertTrue("account reference missing from extracted text", text.contains("7781-224-9"))
        assertTrue("currency missing from extracted text", text.contains("USD"))
        // The stated total the gate reconciles against, and one line's amount.
        assertTrue("printed net movement missing", text.contains("Net movement for the period"))
        assertTrue("stated total missing", text.contains("1,025.00"))
        assertTrue("a transaction amount missing", text.contains("3,200.00"))

        // Guard the fallthrough itself: if either parser's recognition marker
        // ever appears here, this fixture silently stops testing the LLM path.
        assertFalse("would be claimed by DbsStatementParser", text.contains("Account No."))
        assertFalse("would be claimed by BofaStatementParser", text.contains("Account number"))
        assertFalse("would be claimed by BofaStatementParser", text.contains("Beginning balance on"))
    }

    @Test
    fun `recognized DBS layout succeeds via the deterministic path`() {
        val bytes = File("src/test/resources/ledger_fixtures/dbs_happy_path.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("dbs_happy_path.pdf", bytes)
        assertTrue(result is DeterministicResult.Success)
        val txns = (result as DeterministicResult.Success).transactions
        assertTrue(txns.all { it.ingestMethod == IngestMethod.DETERMINISTIC })
    }

    @Test
    fun `a recognized-but-corrupted DBS statement quarantines rather than falling to the LLM path`() {
        val bytes = File("src/test/resources/ledger_fixtures/dbs_balance_mismatch.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("dbs_balance_mismatch.pdf", bytes)
        assertTrue(result is DeterministicResult.Quarantined)
    }

    @Test
    fun `an unrecognized layout falls through to NeedsLlm without crashing, never quietly succeeding`() {
        // dispatchDeterministic never touches Gemini (that's the whole point
        // of the split - see StatementDispatcher's doc comment) - both
        // deterministic parsers correctly decline this layout and it comes
        // back NeedsLlm, carrying the already-extracted text.
        val bytes = File("src/test/resources/ledger_fixtures/unrecognized_layout.pdf").readBytes()
        val result = StatementDispatcher.dispatchDeterministic("unrecognized_layout.pdf", bytes)
        assertTrue(result is DeterministicResult.NeedsLlm)
        assertTrue((result as DeterministicResult.NeedsLlm).statementText.isNotBlank())
        // Deliberately NOT exercising StatementDispatcher.runLlm here - it
        // makes a real HTTP call to the Gemini endpoint, which this repo's
        // rule is to never do from a test (every reachable call bills
        // Kevin's own key, even a request that later fails). runLlm's
        // graceful-failure behavior on a bad/missing key or no network is
        // exercised at the SubAgent.askWithUsage level instead (same
        // try/catch/HttpOutcome shape as the already-tested ask()).
    }
}
