"""`public.purchases`, the household bought log (purchase-log ticket 06).

Born tenanted, and in `public` by the same temporary search_path swap
`push/migrations/0001_initial.py` uses, so it sits beside the other tenant
tables `household.tenancy.TENANT_TABLES` lists. The ADR 0052 owner guard
(`public.legion_owner_is_a_member()`, `household/visibility_sql.py`) is
attached so the database itself refuses a private entry whose owner is not a
member of its household. Nothing here touches the `private` schema, which the
live engine role cannot use.
"""
# Generated by Django 5.2.7 on 2026-10-05 00:55

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models

_SWAP_SEARCH_PATH_TO_PUBLIC_FIRST = migrations.RunSQL(
    sql="SET search_path TO public, django;",
    reverse_sql="SET search_path TO django, public;",
)

_RESTORE_SEARCH_PATH_TO_DJANGO_FIRST = migrations.RunSQL(
    sql="SET search_path TO django, public;",
    reverse_sql="SET search_path TO public, django;",
)


def guard(apps, schema_editor):
    from household.visibility_sql import attach_guard, create_guard_function

    with schema_editor.connection.cursor() as cursor:
        create_guard_function(cursor)
        attach_guard(cursor, "purchases")


def unguard(apps, schema_editor):
    from household.visibility_sql import GUARD_TRIGGER

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"drop trigger if exists {GUARD_TRIGGER} on public.purchases")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checklists", "0004_owner_restrict"),
        ("household", "0004_devicetoken_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        _SWAP_SEARCH_PATH_TO_PUBLIC_FIRST,
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item", models.TextField()),
                ("bought_on", models.IntegerField()),
                (
                    "logged_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("store", models.TextField(blank=True, null=True)),
                ("price_cents", models.BigIntegerField(blank=True, null=True)),
                ("quantity_note", models.TextField(blank=True, null=True)),
                ("source", models.TextField(default="MANUAL")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sync_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="household.household",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tick",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase",
                        to="checklists.checklisttick",
                    ),
                ),
            ],
            options={
                "db_table": "purchases",
                "indexes": [
                    models.Index(
                        fields=["household", "bought_on"],
                        name="purchases_household_day_idx",
                    ),
                    models.Index(
                        models.F("household"),
                        django.db.models.functions.text.Lower("item"),
                        name="purchases_household_item_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "sync_id"),
                        name="purchases_household_sync_id_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source__in",
                                ("MANUAL", "GROCERIES_TICK", "GROCERIES_BACKFILL"),
                            )
                        ),
                        name="purchases_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price_cents__isnull", True),
                            ("price_cents__gte", 0),
                            _connector="OR",
                        ),
                        name="purchases_price_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("source", "MANUAL"), _negated=True),
                            ("tick__isnull", True),
                            _connector="OR",
                        ),
                        name="purchases_manual_has_no_tick",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("item__regex", "^\\s*$"), _negated=True),
                        name="purchases_item_not_blank",
                    ),
                ],
            },
        ),
        _RESTORE_SEARCH_PATH_TO_DJANGO_FIRST,
        migrations.RunPython(guard, unguard),
    ]
