# Generated by Django 5.2.7 on 2026-09-27, then hand-edited (backend-etl ticket
# 02) to add the same temporary search_path swap `0001_initial.py` uses, so
# `source_credentials` lands in `public` beside `ingest_runs` rather than in
# `django`. `checklists/migrations/0001_initial.py`'s header holds the full
# reasoning. Everything Django generated is otherwise untouched.
#
# Born tenanted, like `ingest_runs`: `household` is a real ForeignKey here, so
# `household/migrations/0002`'s SQL loop and `tests/conftest.py`'s second pass
# find the column already present and change nothing.

import django.db.models.deletion
import uuid
from django.db import migrations, models

_SWAP_SEARCH_PATH_TO_PUBLIC_FIRST = migrations.RunSQL(
    sql="SET search_path TO public, django;",
    reverse_sql="SET search_path TO django, public;",
)

_RESTORE_SEARCH_PATH_TO_DJANGO_FIRST = migrations.RunSQL(
    sql="SET search_path TO django, public;",
    reverse_sql="SET search_path TO public, django;",
)


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0003_invite"),
        ("ingest", "0001_initial"),
    ]

    operations = [
        _SWAP_SEARCH_PATH_TO_PUBLIC_FIRST,
        migrations.CreateModel(
            name="SourceCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        choices=[
                            ("canvas", "Canvas"),
                            ("webassign", "WebAssign"),
                            ("drive", "Google Drive"),
                        ]
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("cookie_jar", "Cookie jar"),
                            ("oauth_refresh", "OAuth refresh token"),
                        ]
                    ),
                ),
                ("ciphertext", models.BinaryField()),
                ("captured_at", models.DateTimeField()),
                ("expires_hint", models.DateTimeField(blank=True, null=True)),
                ("invalid_since", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="household.household",
                    ),
                ),
            ],
            options={
                "db_table": "source_credentials",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "source"),
                        name="source_credentials_hh_source_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source__in", ["canvas", "webassign", "drive"])
                        ),
                        name="source_credentials_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["cookie_jar", "oauth_refresh"])
                        ),
                        name="source_credentials_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "cookie_jar"),
                                ("source__in", ["canvas", "webassign"]),
                            ),
                            models.Q(("kind", "oauth_refresh"), ("source", "drive")),
                            _connector="OR",
                        ),
                        name="source_credentials_kind_matches_source",
                    ),
                ],
            },
        ),
        _RESTORE_SEARCH_PATH_TO_DJANGO_FIRST,
    ]
