# Generated by Django 5.2.7 on 2026-09-10 20:19

import django.db.models.deletion
import household.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0002_households_are_tenants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=household.models.generate_invite_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("creates_household", models.BooleanField(default=False)),
                ("max_uses", models.PositiveSmallIntegerField(default=2)),
                ("used_count", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="household.household",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="household_i_code_2d0861_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("creates_household", True),
                            ("household__isnull", False),
                            _connector="OR",
                        ),
                        name="invite_joins_or_creates_a_household",
                    )
                ],
            },
        ),
    ]
