# Generated by Django 5.2.7 on 2026-09-06 03:57, then hand-edited (django-engine
# ticket 04) to add: a temporary search_path swap so these tables land in
# `public` rather than `django`, an `updated_at` touch trigger on all three
# tables, and a trigger backstopping the measured-tick rule that a plain
# CHECK constraint cannot express (it would need to read a DIFFERENT
# table). Everything Django generated is otherwise untouched.
#
# **Why `public`, and why a search_path SET rather than a schema-qualified
# `db_table`.** `legion/settings.py` points the default connection's
# search_path at `django,public` specifically so Django's OWN bookkeeping
# (household_*, auth_*, django_*) never lands in `public`, which
# `supabase/migrations/` owns (execution-plan.md Phase 0). These three
# tables are the opposite case: they are DOMAIN data, meant to sit
# alongside the 41 legacy tables `public` already holds, not server-only
# bookkeeping - this ticket's own brief says so by name ("in the public
# schema"). An unqualified `CREATE TABLE` follows search_path and would
# therefore land in `django` by default (confirmed empirically for exactly
# this reason in `core/migrations/0001_create_django_schema.py`'s own
# comment). A schema-qualified `db_table` (e.g. the classic
# `'"public"."checklists"'` pre-quoted-string trick) was rejected: Django's
# auto-generated constraint/index names are built by string-concatenating
# `db_table`, and feeding one of those a value containing embedded quotes
# and a dot is untested territory this ticket has no reason to risk.
# Temporarily reordering search_path for the duration of just this
# migration's CreateModel operations is surgical by comparison - it changes
# nothing about how the models themselves are declared - and is safe
# because `SET search_path` inside a migration's transaction is itself
# transactional (rolled back with everything else on failure) but persists
# for the rest of the session once the migration COMMITS, which is exactly
# why the second `RunSQL` below restores the original order before this
# migration ends, rather than leaving every later migration in this same
# `migrate` run pointed at the wrong schema.
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models

_SWAP_SEARCH_PATH_TO_PUBLIC_FIRST = migrations.RunSQL(
    sql="SET search_path TO public, django;",
    reverse_sql="SET search_path TO django, public;",
)

_RESTORE_SEARCH_PATH_TO_DJANGO_FIRST = migrations.RunSQL(
    sql="SET search_path TO django, public;",
    reverse_sql="SET search_path TO public, django;",
)

# Reimplemented locally rather than reusing `private.touch_updated_at()`
# (the function `public.events` and every other legacy table's own
# touch-trigger call): that function lives in a schema created by
# `supabase/migrations/`, which a fresh pytest test database - created from
# a bare Postgres template, never from the live Supabase project - does not
# have. This app's tests run exclusively against such a database (per this
# ticket's own instruction not to migrate live), so a dependency on
# `private.*` would fail there while working against the live database,
# exactly the kind of environment-shaped bug worth avoiding by not sharing
# the function at all. Explicitly schema-qualified (`public.`) so its
# location does not depend on whatever search_path happens to be in effect
# when this statement runs.
_CREATE_TOUCH_UPDATED_AT_FUNCTION = migrations.RunSQL(
    sql="""
        create or replace function public.checklists_touch_updated_at()
        returns trigger as $$
        begin
            new.updated_at = now();
            return new;
        end;
        $$ language plpgsql;
    """,
    reverse_sql="drop function if exists public.checklists_touch_updated_at();",
)

_ATTACH_TOUCH_UPDATED_AT_TRIGGERS = migrations.RunSQL(
    sql="""
        create trigger checklists_touch_updated_at
            before update on public.checklists
            for each row execute function public.checklists_touch_updated_at();
        create trigger checklist_items_touch_updated_at
            before update on public.checklist_items
            for each row execute function public.checklists_touch_updated_at();
        create trigger checklist_ticks_touch_updated_at
            before update on public.checklist_ticks
            for each row execute function public.checklists_touch_updated_at();
    """,
    reverse_sql="""
        drop trigger if exists checklists_touch_updated_at on public.checklists;
        drop trigger if exists checklist_items_touch_updated_at on public.checklist_items;
        drop trigger if exists checklist_ticks_touch_updated_at on public.checklist_ticks;
    """,
)

# Backstops `checklists/serializers.py`'s own valueless-measured-tick
# refusal (the same "a check that passes when nothing parsed is not a
# gate" posture CLAUDE.md section 4 rule 6 states for an ingestion path,
# applied here to a write path instead: a rule enforced only in Python is
# not enforced against every writer, e.g. a future management command or a
# raw psql session). Reads `checklist_items.measure_unit` in a join a plain
# table CHECK constraint cannot express (a CHECK may only see columns on
# its OWN row). Fires on both INSERT and UPDATE so a later edit that clears
# a tick's own value cannot bypass the rule either.
_CREATE_MEASURED_TICK_GUARD_FUNCTION = migrations.RunSQL(
    sql="""
        create or replace function public.checklists_enforce_measured_tick()
        returns trigger as $$
        declare
            v_measure_unit text;
        begin
            if new.value is null then
                select measure_unit into v_measure_unit
                from public.checklist_items
                where id = new.item_id;
                if v_measure_unit is not null then
                    raise exception
                        'checklist item % is measured in % - a tick needs a value, nothing was recorded',
                        new.item_id, v_measure_unit;
                end if;
            end if;
            return new;
        end;
        $$ language plpgsql;
    """,
    reverse_sql="drop function if exists public.checklists_enforce_measured_tick();",
)

_ATTACH_MEASURED_TICK_GUARD_TRIGGER = migrations.RunSQL(
    sql="""
        create trigger checklist_ticks_enforce_measured
            before insert or update on public.checklist_ticks
            for each row execute function public.checklists_enforce_measured_tick();
    """,
    reverse_sql="""
        drop trigger if exists checklist_ticks_enforce_measured on public.checklist_ticks;
    """,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        _SWAP_SEARCH_PATH_TO_PUBLIC_FIRST,
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("schedule_kind", models.TextField(blank=True, null=True)),
                ("schedule_every", models.IntegerField(blank=True, null=True)),
                ("schedule_days_of_week", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "checklists",
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "measure_unit",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("measure_target", models.FloatField(blank=True, null=True)),
                (
                    "measure_direction",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="checklists.checklist",
                    ),
                ),
            ],
            options={
                "db_table": "checklist_items",
            },
        ),
        migrations.CreateModel(
            name="ChecklistTick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.IntegerField()),
                (
                    "ticked_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("value", models.FloatField(blank=True, null=True)),
                ("source", models.TextField(default="USER_REPORTED")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="checklists.checklistitem",
                    ),
                ),
            ],
            options={
                "db_table": "checklist_ticks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "day"), name="checklist_ticks_item_day_uniq"
                    )
                ],
            },
        ),
        _RESTORE_SEARCH_PATH_TO_DJANGO_FIRST,
        _CREATE_TOUCH_UPDATED_AT_FUNCTION,
        _ATTACH_TOUCH_UPDATED_AT_TRIGGERS,
        _CREATE_MEASURED_TICK_GUARD_FUNCTION,
        _ATTACH_MEASURED_TICK_GUARD_TRIGGER,
    ]
