# Generated by Django 5.2.7 on 2026-10-05 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0004_owner_restrict"),
        ("household", "0004_devicetoken_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="system_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name="checklist",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("system_key__isnull", False)
                ),
                fields=("household", "system_key"),
                name="checklists_household_system_key_uniq",
            ),
        ),
    ]
