"""Generate docs/devlog.html - what was built, when, and which ticket authorised it.

Kevin, 2026-08-22: *"everything we build should leave an auditable and tracable ticket. all
decisions in ADR or etc. leave a dev log or some kind of documentation."*

The pieces already existed and did not join up. Tickets say what is planned. `decisions.md` says
what was decided and when. ADRs say what is binding now. `docs/index.html` says what is still open.
**Nothing said what actually shipped**, and git log is the only thing that knows - which is fine
until you want to answer "when did the socket fix land, and what decided it" without reading two
hundred commit messages.

This walks the history, pulls every ticket reference out of each commit message, and renders a
reverse-chronological log linking a commit to the ticket that authorised it. A commit naming no
ticket is rendered as **unlinked**, visibly and on purpose, because that is the thing worth seeing:
work with no traceable decision behind it.

**A bare "ticket 06" only resolves when exactly one map named in the same message has a ticket 06.**
Ticket numbers repeat across maps, and a confidently wrong link is worse than an honest blank.

Generated, never hand-edited. Re-run after committing; the commit hook does it too.

    python tools/devlog.py            # write docs/devlog.html
    python tools/devlog.py --check    # list unlinked commits in the recent window
"""
import glob
import io
import os
import re
import subprocess
import sys

OUT = "docs/devlog.html"
REPO = "https://github.com/kevinmyo-code/legion"
MAX_COMMITS = 400
SEP = "\x1e"
REC_SEP = "\x1d"

PATH_REF = re.compile(r"\.scratch/([a-z0-9-]+)/issues/(\d+)-", re.I)
NAMED_REF = re.compile(r"([a-z][a-z0-9-]+)\s+(?:ticket\s+)?(\d+)", re.I)
BARE_REF = re.compile(r"\bticket\s+(\d+)\b", re.I)


def sh(args):
    return subprocess.run(args, capture_output=True, text=True, encoding="utf-8",
                          errors="replace").stdout


def known_tickets():
    """(map, num) -> (path, title) for every ticket on disk, so a reference can be resolved."""
    out = {}
    for path in glob.glob(".scratch/*/issues/*.md"):
        p = path.replace("\\", "/")
        m = re.match(r"\.scratch/([^/]+)/issues/(\d+)-", p)
        if not m:
            continue
        head = io.open(p, encoding="utf-8", errors="replace").read()[:600]
        title = re.search(r'^title:\s*"?(.*?)"?\s*$', head, re.M)
        out[(m.group(1), m.group(2))] = (p, title.group(1) if title else p)
    return out


def norm(num):
    return num.lstrip("0").zfill(2)


def refs_in(text, tickets, maps):
    found = set()
    for m in PATH_REF.finditer(text):
        found.add((m.group(1).lower(), norm(m.group(2))))
    for m in NAMED_REF.finditer(text):
        key = (m.group(1).lower(), norm(m.group(2)))
        if key in tickets:
            found.add(key)
    if not found:
        named = [s for s in maps if s in text.lower()]
        for m in BARE_REF.finditer(text):
            hits = [(s, norm(m.group(1))) for s in named
                    if (s, norm(m.group(1))) in tickets]
            if len(hits) == 1:
                found.add(hits[0])
    return sorted(k for k in found if k in tickets)


def commits():
    fmt = SEP.join(["%H", "%h", "%ad", "%s", "%b"]) + REC_SEP
    raw = sh(["git", "log", "-n", str(MAX_COMMITS), "--date=short", "--format=" + fmt])
    for chunk in raw.split(REC_SEP):
        if not chunk.strip():
            continue
        parts = chunk.strip("\n").split(SEP)
        if len(parts) < 5:
            continue
        yield dict(full=parts[0], short=parts[1], date=parts[2],
                   subject=parts[3], body=parts[4])


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


STYLE = """<!-- generated by tools/devlog.py - do not hand-edit -->
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>LEGION dev log</title>
<style>
:root{--bg:#141A22;--panel:#1E2530;--ink:#E4E9EF;--dim:#8E97A3;--line:#2A3340;
--ok:#57EFC6;--warn:#FFBA1F}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font:14px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;padding:24px}
h1{font-size:19px;margin:0 0 4px;letter-spacing:.08em}
.sub{color:var(--dim);margin:0 0 20px;font-size:12px}
.sub a{color:var(--ok)}
.day{color:var(--dim);font-size:11px;letter-spacing:.14em;margin:22px 0 8px;
border-bottom:1px solid var(--line);padding-bottom:4px}
.c{background:var(--panel);border:1px solid var(--line);border-left:2px solid var(--ok);
border-radius:3px;padding:10px 12px;margin-bottom:7px;cursor:pointer}
.c.unlinked{border-left-color:var(--warn)}
.s{font-weight:600}
.meta{color:var(--dim);font-size:11px;margin-top:5px}
.meta a{color:var(--dim)}
.t{display:inline-block;background:#17453A;color:var(--ok);border-radius:2px;
padding:1px 6px;margin:3px 4px 0 0;font-size:11px;text-decoration:none}
.t.none{background:#4A3A12;color:var(--warn)}
.body{color:var(--dim);font-size:12px;margin-top:6px;white-space:pre-wrap;
display:none;border-top:1px dashed var(--line);padding-top:6px}
.c.open .body{display:block}
</style>
<h1>LEGION DEV LOG</h1>
<p class="sub">What actually shipped, newest first, linked to the ticket that authorised it.
Generated by <code>tools/devlog.py</code> &middot; <a href="index.html">open tickets</a>
&middot; <a href="voice.html">voice guide</a><br>
An amber edge means the commit names no ticket. Click a commit for its full message.</p>
"""


def render(rows, tickets):
    parts = [STYLE]
    day = None
    for c in rows:
        if c["date"] != day:
            day = c["date"]
            parts.append('<div class="day">%s</div>' % day)
        chips = []
        for key in c["refs"]:
            path, title = tickets[key]
            chips.append('<a class="t" href="%s/blob/dev/%s" title="%s">%s %s</a>'
                         % (REPO, path, esc(title), key[0], key[1]))
        if not chips:
            chips.append('<span class="t none">no ticket</span>')
        parts.append(
            '<div class="c%s" onclick="this.classList.toggle(&quot;open&quot;)">'
            '<div class="s">%s</div>%s'
            '<div class="meta"><a href="%s/commit/%s">%s</a> &middot; %d file%s</div>'
            '<div class="body">%s</div></div>'
            % ("" if c["refs"] else " unlinked", esc(c["subject"]), "".join(chips),
               REPO, c["full"], c["short"], c["files"],
               "" if c["files"] == 1 else "s", esc(c["body"].strip())))
    return "\n".join(parts) + "\n"


def main():
    tickets = known_tickets()
    maps = set(m for m, _ in tickets)
    rows = []
    for c in commits():
        names = [n.strip().replace("\\", "/")
                 for n in sh(["git", "show", "--name-only", "--format=", c["full"]]).splitlines()
                 if n.strip()]
        c["files"] = len(names)
        # Strongest signal first, and it is a fact rather than an inference: a commit that TOUCHED
        # a ticket file IS linked to that ticket. Committing the ticket alongside the code is the
        # habit this whole traceability rule exists to make normal, so reward it directly instead
        # of trying to parse intent out of prose.
        refs = set()
        for n in names:
            m = PATH_REF.match(n)
            if m:
                refs.add((m.group(1).lower(), norm(m.group(2))))
        refs.update(refs_in(c["subject"] + "\n" + c["body"], tickets, maps))
        c["refs"] = sorted(k for k in refs if k in tickets)
        rows.append(c)
    if "--check" in sys.argv:
        recent = [c for c in rows[:25] if not c["refs"]]
        for c in recent:
            print("unlinked: %s %s" % (c["short"], c["subject"]))
        print("%d of the last %d commits name no ticket" % (len(recent), min(25, len(rows))))
        return 0
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(render(rows, tickets))
    linked = sum(1 for c in rows if c["refs"])
    print("%s: %d commits, %d linked, %d unlinked"
          % (OUT, len(rows), linked, len(rows) - linked))
    return 0


if __name__ == "__main__":
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    sys.exit(main())
