#!/usr/bin/env python3
"""Emit the shared gate corpus as one self-rolling-back SQL script.

Ticket 03 ruling 2 accepted two implementations of the reconciliation arithmetic - a Kotlin
pre-check on the phone and the SQL inside `commit_statement`/`commit_receipt` - on the condition
that something proves they agree. `app/src/test/resources/gate-corpus.json` is that something.
`GateCorpusTest.kt` checks it from the Kotlin side; this script emits the identical cases for the
RPC side.

Both sides read the SAME file, which is the whole point. A case can only pass both by being right,
and a divergence shows up as one side disagreeing with a corpus the other side agrees with.

The emitted script ends in a deliberate `raise`, so the whole thing rolls back and no test row
survives in the household's database. It reports every case's actual outcome against its expected
one and names any mismatch.

Usage:
    python tools/gate_corpus_sql.py            # print the SQL
    python tools/gate_corpus_sql.py -o out.sql # write it

Then paste into the Supabase SQL editor and run. There is no local Postgres on this machine (see
tools/sql_check.py), so this is executed against the real project rather than in CI.
"""

import json
import os
import sys

CORPUS = os.path.join("app", "src", "test", "resources", "gate-corpus.json")


def sql_str(value):
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def jsonb(value):
    """A jsonb literal, single-quotes doubled so it survives being embedded in SQL."""
    return "'" + json.dumps(value).replace("'", "''") + "'::jsonb"


def build() -> str:
    with open(CORPUS, encoding="utf-8") as handle:
        corpus = json.load(handle)

    out = [
        "-- GENERATED by tools/gate_corpus_sql.py from app/src/test/resources/gate-corpus.json.",
        "-- Do not edit here; edit the corpus and regenerate, or the two sides stop sharing a source.",
        "--",
        "-- Ends in a deliberate RAISE so the whole transaction rolls back. Nothing survives.",
        "do $$",
        "declare",
        "  r jsonb;",
        "  actual text;",
        "  failures text := '';",
        "  checked integer := 0;",
        "begin",
    ]

    for i, case in enumerate(corpus.get("ledger", [])):
        # A case with no "provenance" key is a pre-amendment (2026-08-27) three-anchor case and
        # defaults to DETERMINISTIC, same default GateCorpusTest.kt uses - the two sides must agree
        # on what an absent key means, not just on what an explicit one means.
        # "stated_total_cents" may be JSON null now (ticket 12's amendment): a bank that prints no
        # combined total. `.get()` rather than `[...]` passes that null straight through to the
        # payload, which is exactly what `commit_statement` must see to exercise its own null branch.
        payload = {
            "content_sha256": f"corpus-ledger-{i}",
            "account_last4": "1234",
            "account_nickname": "corpus",
            "currency": "USD",
            "provenance": case.get("provenance", "DETERMINISTIC"),
            "stated_total_cents": case.get("stated_total_cents"),
            "opening_balance_cents": case["opening_balance_cents"],
            "closing_balance_cents": case["closing_balance_cents"],
            "lines": [
                {
                    "txn_date": line["txn_date"],
                    "description": line["description"],
                    "amount_cents": line["amount_cents"],
                    "line_ref": f"corpus-{i}-{n}",
                }
                for n, line in enumerate(case["lines"])
            ],
        }
        out += [
            "",
            f"  -- ledger: {case['name']}",
            f"  r := public.commit_statement({jsonb(payload)});",
            "  actual := r ->> 'outcome';",
            "  checked := checked + 1;",
            f"  if actual <> {sql_str(case['expect'])} then",
            f"    failures := failures || E'\\n  LEDGER {case['name'].replace(chr(39), chr(39) * 2)}"
            f": expected {case['expect']}, got ' || coalesce(actual, 'null');",
            "  end if;",
        ]

    for i, case in enumerate(corpus.get("pantry", [])):
        payload = {
            "content_sha256": f"corpus-pantry-{i}",
            "store": "CORPUS",
            "purchase_date": "2026-07-15",
            "currency": "SGD",
            "provenance": "LLM_RECONCILED",
            "total_cents": case["total_cents"],
            "subtotal_cents": case.get("subtotal_cents"),
            "tax_cents": case.get("tax_cents"),
            "other_charges_cents": case.get("other_charges_cents"),
            "items": case["items"],
        }
        payload = {k: v for k, v in payload.items() if v is not None or k == "subtotal_cents"}
        out += [
            "",
            f"  -- pantry: {case['name']}",
            f"  r := public.commit_receipt({jsonb(payload)});",
            "  actual := r ->> 'outcome';",
            "  checked := checked + 1;",
            f"  if actual <> {sql_str(case['expect'])} then",
            f"    failures := failures || E'\\n  PANTRY {case['name'].replace(chr(39), chr(39) * 2)}"
            f": expected {case['expect']}, got ' || coalesce(actual, 'null');",
            "  end if;",
        ]

    out += [
        "",
        "  if failures = '' then",
        "    raise exception E'GATE CORPUS: all % cases agree. (rolled back)', checked;",
        "  else",
        "    raise exception E'GATE CORPUS: % cases checked, MISMATCHES:%', checked, failures;",
        "  end if;",
        "end $$;",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    if not os.path.exists(CORPUS):
        print(f"corpus not found at {CORPUS}", file=sys.stderr)
        return 2
    sql = build()
    if "-o" in sys.argv:
        target = sys.argv[sys.argv.index("-o") + 1]
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(sql)
        print(f"wrote {target} ({len(sql)} chars)")
    else:
        print(sql)
    return 0


if __name__ == "__main__":
    sys.exit(main())
