package com.kevin.legion.ui.help

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.kevin.legion.ui.common.DeckScreenHeader
import com.kevin.legion.ui.common.DeckTextField
import com.kevin.legion.ui.common.Hairline
import com.kevin.legion.ui.common.SectionHeader
import com.kevin.legion.ui.theme.LegionType
import com.kevin.legion.ui.theme.LocalLegionSemantics

/**
 * The in-app "What can I do" screen (command-center ticket 09,
 * `.scratch/command-center/issues/09-discovery-and-wiki.md`) - Kevin: *"i need to know what the
 * app does, users need a wiki on what the app can do."* Everything it renders comes from
 * [VoiceGuideData], generated by `python tools/voice_guide.py` from the exact same
 * `tools/voice_guide_copy.py` that feeds `docs/voice.html`. **This screen has no copy of its own
 * to drift** - it is a renderer over generated data, same posture as `docs/voice.html`'s own
 * `render()`.
 *
 * Grouped by domain (the same 13 groups `docs/voice.html` uses), with a simple contains-filter
 * search across the tool's name, spoken example, description, and hands-path line - deliberately
 * NOT a fuzzy search, so "what it actually matched" is always obvious from what is on screen.
 *
 * Every entry shows its hands path per ADR 0035 (`docs/adr/0035-every-voice-capability-has-a-hands-path.md`):
 * "Voice only." is shown with the same weight as a real path, never hidden or softened - the whole
 * point of the field existing is to be honest about the gap, not to bury it.
 */
@Composable
fun VoiceGuideScreen(onBack: () -> Unit) {
    var query by remember { mutableStateOf("") }
    val sem = LocalLegionSemantics.current

    val filteredGroups = remember(query) { filterGroups(VoiceGuideData.GROUPS, query) }
    val totalShown = filteredGroups.sumOf { it.entries.size }

    Surface(modifier = Modifier.fillMaxSize()) {
        Column(Modifier.fillMaxSize()) {
            DeckScreenHeader(title = "What can I do", onBack = onBack)
            Column(Modifier.padding(horizontal = 16.dp)) {
                Spacer(Modifier.height(12.dp))
                Text(
                    VoiceGuideData.INTRO,
                    style = LegionType.stamp,
                    color = sem.faint,
                )
                Spacer(Modifier.height(4.dp))
                Text(
                    "Full guide on the project page: docs/voice.html",
                    style = LegionType.stamp,
                    color = sem.faint,
                )
                Spacer(Modifier.height(12.dp))
                DeckTextField(
                    value = query,
                    onValueChange = { query = it },
                    label = "Search what it can do",
                    modifier = Modifier.fillMaxWidth(),
                )
                Spacer(Modifier.height(4.dp))
                Text(
                    "$totalShown of ${VoiceGuideData.TOOL_COUNT} things it can do",
                    style = LegionType.stamp,
                    color = sem.ghost,
                )
                Spacer(Modifier.height(8.dp))
            }
            LazyColumn(Modifier.fillMaxSize().padding(horizontal = 16.dp)) {
                filteredGroups.forEach { group ->
                    item(key = "header-${group.title}") {
                        Spacer(Modifier.height(12.dp))
                        SectionHeader(left = group.title, right = "${group.entries.size}")
                        group.blurb?.let {
                            Text(it, style = LegionType.stamp, color = sem.faint)
                        }
                        Spacer(Modifier.height(4.dp))
                    }
                    items(group.entries, key = { it.name }) { entry ->
                        VoiceGuideEntryRow(entry)
                        Hairline()
                    }
                }
                if (filteredGroups.isEmpty()) {
                    item {
                        Spacer(Modifier.height(24.dp))
                        Text(
                            "Nothing matches \"$query\".",
                            style = LegionType.reading,
                            color = sem.faint,
                        )
                    }
                }
                item { Spacer(Modifier.height(24.dp)) }
            }
        }
    }
}

@Composable
private fun VoiceGuideEntryRow(entry: VoiceGuideData.Entry) {
    val sem = LocalLegionSemantics.current
    Column(Modifier.fillMaxWidth().padding(vertical = 8.dp)) {
        Text(
            "“${entry.say}”",
            style = LegionType.reading.copy(fontWeight = FontWeight.Bold),
            color = MaterialTheme.colorScheme.onSurface,
        )
        Spacer(Modifier.height(2.dp))
        Text(entry.does, style = LegionType.stamp, color = sem.faint)
        Spacer(Modifier.height(2.dp))
        Row {
            Text("By hand: ", style = LegionType.stamp, color = sem.ghost)
            Text(entry.hands, style = LegionType.stamp, color = sem.ghost)
        }
    }
}

/**
 * A tool matches if the query is a plain substring (case-insensitive) of its name, spoken
 * example, description, hands note, or group title - so searching "fuel stop" finds
 * `log_pending_transaction` through its `does` text even though the name itself does not contain
 * the phrase. Groups with zero surviving entries are dropped rather than shown empty. A blank
 * query returns every group unchanged.
 */
internal fun filterGroups(groups: List<VoiceGuideData.Group>, query: String): List<VoiceGuideData.Group> {
    val q = query.trim()
    if (q.isEmpty()) return groups
    return groups.mapNotNull { group ->
        val matches = group.entries.filter { entry -> entryMatches(entry, group.title, q) }
        if (matches.isEmpty()) null else group.copy(entries = matches)
    }
}

internal fun entryMatches(entry: VoiceGuideData.Entry, groupTitle: String, query: String): Boolean {
    val q = query
    return entry.name.contains(q, ignoreCase = true) ||
        entry.say.contains(q, ignoreCase = true) ||
        entry.does.contains(q, ignoreCase = true) ||
        entry.hands.contains(q, ignoreCase = true) ||
        groupTitle.contains(q, ignoreCase = true)
}
