"""`server/openapi.yaml` is the contract, so it is tested like one.

django-engine ticket 04: "`manage.py spectacular --file server/openapi.yaml`,
committed, regenerated by a test that fails when the committed file is
stale. Ticket 09 codes against this file." A second Android app generates
its client from it too. That makes the file's failure mode specific and
nasty: it does not crash, it quietly describes an API that used to exist,
and the mistake surfaces as a decode failure on someone's phone rather than
as a red build here.

Three checks, in order of what they catch.

1. **Staleness.** Regenerate into a temp file, compare, fail naming the one
   command that fixes it. `write_openapi` runs `spectacular` with
   `--fail-on-warn` and `--validate`, so this test ALSO fails when a new
   view cannot be described (drf-spectacular's "unable to guess serializer")
   or when the document is not valid OpenAPI - a view added without an
   `@extend_schema` is caught here, not discovered by whoever generates a
   client from it.

2. **The security scheme exists.** Without the `OpenApiAuthenticationExtension`
   in `api/schema.py`, drf-spectacular silently omits `security:` from the
   whole document, and a generated client has no idea the
   `Authorization: Token <key>` header exists. It is silent precisely
   because nothing breaks - hence a test.

3. **The schema against a real response.** This is the check that would have
   caught the bug this test file was written alongside: every `?since=` list
   route answers `{"results": [...], "next": ...}`, and the schema described
   them as a BARE ARRAY of rows. Nothing was broken, no warning fired, and
   the document was valid OpenAPI the whole time. Comparing the declared
   properties against the keys a real call actually returns is the only kind
   of check that finds that class of lie.
"""
from __future__ import annotations

import uuid

import pytest
import yaml
from django.core.management import call_command

from api.management.commands.write_openapi import schema_path

REGENERATE = "cd server && uv run manage.py write_openapi"


def _committed_schema() -> dict:
    return yaml.safe_load(schema_path().read_text(encoding="utf-8"))


def test_committed_openapi_schema_is_not_stale(tmp_path):
    """Fails when `server/openapi.yaml` no longer matches the URL conf.

    Also fails when the schema cannot be generated cleanly at all, because
    `write_openapi` passes `--fail-on-warn`: a view drf-spectacular cannot
    describe raises a `CommandError` here rather than landing in the file as
    a silently omitted path.
    """
    committed = schema_path()
    assert committed.exists(), (
        f"{committed} is missing. It is the contract ticket 09 and the second Android app "
        f"generate clients from, and it is committed on purpose. Run: {REGENERATE}"
    )

    regenerated = tmp_path / "openapi.yaml"
    call_command("write_openapi", file=str(regenerated))

    # Compared line by line, not byte by byte: `.gitattributes` pins this
    # file to LF so the two should be identical on disk, but an editor that
    # rewrote the line endings would otherwise fail this test with a diff
    # nobody can see, which is a worse message than no test.
    expected = regenerated.read_text(encoding="utf-8").splitlines()
    actual = committed.read_text(encoding="utf-8").splitlines()
    if actual != expected:
        first = next(
            # `strict=False`: the two files routinely differ in LENGTH, which
            # is the whole point of this branch. `zip` stops at the shorter
            # one and the `min(...)` default below reports the first line
            # past its end.
            (i for i, (a, b) in enumerate(zip(actual, expected, strict=False)) if a != b),
            min(len(actual), len(expected)),
        )
        pytest.fail(
            f"server/openapi.yaml is STALE - the API has changed and the committed contract "
            f"has not. A client generated from this file would be built against an API that "
            f"no longer exists.\n\n"
            f"Run: {REGENERATE}\n\n"
            f"First difference at line {first + 1}:\n"
            f"  committed:   {actual[first] if first < len(actual) else '<end of file>'}\n"
            f"  regenerated: {expected[first] if first < len(expected) else '<end of file>'}"
        )


def test_schema_declares_the_device_token_security_scheme():
    """The one fact a generated client most needs, and the one that goes
    missing without a sound - see this module's doc comment."""
    schema = _committed_schema()
    schemes = schema["components"]["securitySchemes"]
    assert "deviceToken" in schemes, (
        "No device-token security scheme in the schema. A client generated from this file "
        "would send no Authorization header and 401 on every call. The extension is "
        "`api.schema.DeviceTokenScheme`, registered by `api/apps.py`'s `ready()`."
    )
    assert schemes["deviceToken"]["in"] == "header"
    assert schemes["deviceToken"]["name"] == "Authorization"

    # Every authenticated operation carries it; only login and the health
    # check are open, and they say so with an empty requirement.
    listed = schema["paths"]["/api/places/"]["get"]["security"]
    assert {"deviceToken": []} in listed
    assert schema["paths"]["/api/auth/login"]["post"]["security"] == [{}]


def _properties_of_200(schema: dict, path: str, method: str = "get") -> dict:
    ref = schema["paths"][path][method]["responses"]["200"]["content"]["application/json"][
        "schema"
    ]["$ref"]
    return schema["components"]["schemas"][ref.rsplit("/", 1)[-1]]["properties"]


@pytest.mark.django_db
def test_declared_list_response_matches_a_real_synced_list_call(auth_client):
    """`GET /api/places/` really returns the paged envelope, and the schema
    really says so. Before `api/schema.SyncedAutoSchema` existed this
    returned an object and the schema promised an array - checked against
    the deployed engine on 2026-09-07, which returns
    `{"results": [...], "next": null}`."""
    schema = _committed_schema()
    declared = _properties_of_200(schema, "/api/places/")

    response = auth_client.get("/api/places/?active=1")
    assert response.status_code == 200
    assert set(response.json()) == set(declared), (
        "The schema and the endpoint disagree about the top-level keys of a list response."
    )
    assert set(declared) == {"results", "next"}


@pytest.mark.django_db
def test_declared_list_response_matches_a_real_events_call(auth_client):
    """`/api/events` is hand-written rather than on the generic viewset, so
    it gets its own check - the two shapes are meant to be the same and
    nothing but a test keeps them so."""
    schema = _committed_schema()
    declared = _properties_of_200(schema, "/api/events")

    response = auth_client.get("/api/events")
    assert response.status_code == 200
    assert set(response.json()) == set(declared)


@pytest.mark.django_db
def test_every_key_the_changes_feed_returns_is_declared(auth_client):
    """The feed's keys are one per TABLE and are built from
    `api/registry.py`; the schema's are built from the same list. A table
    routed into the feed and missing from the contract would leave a
    generated client with nowhere to decode it, so the real response is
    compared against the declaration rather than trusted to match."""
    schema = _committed_schema()
    declared = _properties_of_200(schema, "/api/changes")

    response = auth_client.get("/api/changes")
    assert response.status_code == 200
    body = response.json()
    undeclared = sorted(set(body) - set(declared))
    assert not undeclared, (
        f"GET /api/changes returns keys the schema does not declare: {undeclared}. "
        f"Run: {REGENERATE}"
    )
    assert "server_time" in body


@pytest.mark.django_db
def test_declared_404_matches_the_real_one(auth_client):
    """A PUT to a `voice_notes` id the server never minted is a 404 with a
    `detail`, not an insert (ticket 04: "the `id` form never inserts"). The
    schema declares that 404; this is the check that it is not fiction."""
    schema = _committed_schema()
    responses = schema["paths"]["/api/voice_notes/{identity}/"]["put"]["responses"]
    assert "404" in responses

    unminted = uuid.uuid4()
    response = auth_client.put(
        f"/api/voice_notes/{unminted}/",
        {"started_at": "2026-01-01T00:00:00Z", "kind": "SOLO"},
        format="json",
    )
    assert response.status_code == 404
    ref = responses["404"]["content"]["application/json"]["schema"]["$ref"]
    declared = schema["components"]["schemas"][ref.rsplit("/", 1)[-1]]["properties"]
    assert set(response.json()) == set(declared) == {"detail"}
